### ISSUE TITLE
Lost my password and seeds

### ISSUE THREAD

**Issue by BaldiDerp** [pooler/electrum-ltc#100]
Hey,

I hope someone can help. I have an electrum ltc wallet. and am my password and seeds wkijt. is it possible to retrieve it somewhere again? I hope very much, had bought a litecoin for nice start of the summer. and this is now rising nicely.

Sorry for my bad englisch

**Comment by pooler** [comment]
If it were possible to access your wallet without knowing the password or to restore it without knowing the seed, your wallet wouldn't be secure.

If you have an idea of what the password might be, you could attempt to recover it by brute force. I will not assist you with that, though.
