### ISSUE TITLE
Accidentally sent LTC to old wallet address

### ISSUE THREAD

**Issue by hysterical1** [pooler/electrum-ltc#101]
Hey, so I bought some LTC and didn't notice that I still had my old wallet dress copied from a previous transaction. Its been over 12 hours and it still hasn't showed up in the receiving tab of my electrum-ltc wallet. Is there anything I can do?

Appreciate everyones help

**Comment by pooler** [comment]
Does the transaction show as confirmed on block explorers?
Is your Electrum-LTC connected and synchronized? Maybe provide a screenshot of the network dialog.

**Comment by hysterical1** [comment]
I got it figured out, thanks so much

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
