### ISSUE TITLE
I just accidentally sent litecoin to my bitcoin electrum wallet and it is not showing up.

### ISSUE THREAD

**Issue by brandonkgreene** [pooler/electrum-ltc#107]
I was trying to convert litecoin to vertcoin using coinbase and shapeshift. Coinbase says that the litecoin has been sent and verified several times, and is unspent. The address is correcct with my electrum wallet, but its not showing up in the wallet. I downloaded the electrum wallet because i read that it could also hold vertcoin. I have been desperately trying to purchase vertcoin for a few days. Is the bitcoin electrum wallet compatible with vertcoin?  Will the litecoin go back to coinbase? How do I retrieve it?

**Comment by brandonkgreene** [comment]
shapeshift timed out and never received the litecoin so i'm assuming coinbase tried to directly send it to my electrum wallet

**Comment by pooler** [comment]
Sorry but I don't understand. You sent litecoins from Coinbase to Shapeshift, so how does Electrum-LTC get into the equation? You cannot use Electrum-LTC to receive or send cryptocurrencies other than Litecoin.

**Comment by ilius** [comment]
I'm confused as well.
Please note that, neither of Electrum-based wallets can hold more than one coin.

- Electrum holds only Bitcoin only
- Electrum-LTC holds only Litecoin only
- Electrum-VTC holds only Vertcoin only

What do you mean ShapeShift timed out? Do you have the web page url for the exchange? (check your browser history)
If you are sure that you sent out some coins to the address given to you by ShapeShift, but didn't receive anything, you should contact ShapeShift.

**Comment by brandonkgreene** [comment]
I had downloaded the Electrum wallet for someplace to store vertcoin. I then went to shapeshift to send the litecoin to convert it to vertcoin and forward it to the wallet somehow it never went through shapeshift.  Shapeshift timed out and really never started the transaction. The only thing that I can figure is that shapeshift must have another address that I was suppose to send it to and somehow I missed it. According to coinbase the litecoin was successfully sent to the address in my electrum wallet. I did this twice in a row before I realized that the litecoin had actually been sent from coinbase. I'm not very good on computers and always seem to go around and around in circles sometimes for hours before I do it right and get something to work. 

    On Thursday, December 28, 2017 9:18 AM, pooler <notifications@github.com> wrote:
 

 Sorry but I don't understand. You sent litecoins from Coinbase to Shapeshift, so how does Electrum-LTC get into the equation? You cannot use Electrum-LTC to receive or send cryptocurrencies other than Litecoin.—

**Comment by brandonkgreene** [comment]
I'm also confused if you cant get the electrum wallet to accept several different currencies. Then why does it have the fiat button with a list of several different crypto currencies that allow you to turn it into whatever currency wallet that you want? Is that list of crypto currencies there for another reason. 

    On Thursday, December 28, 2017 9:18 AM, pooler <notifications@github.com> wrote:
 

 Sorry but I don't understand. You sent litecoins from Coinbase to Shapeshift, so how does Electrum-LTC get into the equation? You cannot use Electrum-LTC to receive or send cryptocurrencies other than Litecoin.—

**Comment by brandonkgreene** [comment]
No it wasn't the address from shapeshift. I accidentally sent the litecoin to the address in my vertcoin wallet when I was trying to use shapeshift.Is there anyway to retrieve it or is it lost forever. Coinbase says that it was sucessfully sent to the address in my vertcoin wallet so I went into fiat and changed it from vertcoin to litecoin. Now the wallet reads litecoin when i open it. 

    On Thursday, December 28, 2017 1:23 PM, Saeed Rasooli <notifications@github.com> wrote:
 

 I'm confused as well.
Please note that, neither of Electrum-based wallets can hold more than one coin.   
   - Electrum holds only Bitcoin only
   - Electrum-LTC holds only Litecoin only
   - Electrum-VTC holds only Vertcoin only
What do you mean ShapeShift timed out? Do you have the web page url for the exchange? (check your browser history)
If you are sure that you sent out some coins to the address given to you by ShapeShift, but didn't receive anything, you should contact ShapeShift.—

**Comment by pooler** [comment]
This is supposed to be a bug tracker, not a help forum, so I'm closing the ticket as off-topic. You may want to ask your questions on a [forum](https://litecointalk.io/) or in [r/litecoin](https://www.reddit.com/r/litecoin/) instead.

**Comment by brandonkgreene** [comment]
sorry about that I thought I was on a help forum 

    On Friday, December 29, 2017 1:40 AM, pooler <notifications@github.com> wrote:
 

 This is supposed to be a bug tracker, not a help forum, so I'm closing the ticket as off-topic. You may want to ask your questions on a forum or in r/litecoin instead.—
