### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by asymmetric** [pooler/electrum-ltc#108]
Hi, is Python 2 still supported, or is this just meant to be run on Python 3? 

I ask because I saw commits [like this one](https://github.com/pooler/electrum-ltc/commit/c3388d967723965ecaff9663ddc9ada50a5dbee6#diff-2eeaed663bd0d25b7e608891384b7298).

In either case, it might be useful to update the README to mention compatibility.

**Comment by pooler** [comment]
The version in the git repo requires Python 3, just like the original Electrum.

Any changes that are not specific to Litecoin should be proposed upstream.

**Comment by asymmetric** [comment]
Thanks!

What about the latest released version? Is it [Python 2.7+](https://github.com/pooler/electrum-ltc/blob/36712dafc001d49f0c43d906fceba871c061baab/setup.py#L15) only or is Python 3 supported as well?

**Comment by pooler** [comment]
Versions of Electrum before 3.0 require Python 2.7, and that includes the current stable release of Electrum-LTC, 2.9.3.1.
