### ISSUE TITLE
  error: invalid command 'bdist_wheel'

### ISSUE THREAD

**Issue by jidanni** [pooler/electrum-ltc#115]
```
# pip2 install https://electrum-ltc.org/download/Electrum-LTC-2.9.3.1.tar.gz
...
error: invalid command 'bdist_wheel'
```
[pip2.txt](https://github.com/pooler/electrum-ltc/files/1608344/pip2.txt)

Debian Release: buster/sid
  APT prefers experimental
  APT policy: (990, 'experimental'), (500, 'unstable')
Architecture: amd64 (x86_64)
Kernel: Linux 4.14.0-2-amd64 (SMP w/1 CPU core)

**Comment by pooler** [comment]
Closing because version 2.9.3.1, and consequently Python 2, are now unsupported.
