### ISSUE TITLE
Always must kill to finally get out of wait_for_tstate_lock

### ISSUE THREAD

**Issue by jidanni** [pooler/electrum-ltc#118]
3.0.3 never cleanly shuts down when the GUI shuts down, but instead has to be stopped via keyboard interrupt.
```
$ electrum-ltc-master/electrum-ltc --testnet
Warning: package scrypt not available, using fallback
  C-c C-cException ignored in: <module 'threading' from '/usr/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
```

**Comment by jidanni** [comment]
One always sees the word 'synchronizing ...' on the GUI.
It uses all the CPU but no network traffic.

**Comment by pooler** [comment]
You are missing the scrypt package, so it is normal for synchronization to be extremely slow.

**Comment by jidanni** [comment]
OK, please add that to
```
Warning: package scrypt not available, using fallback
```
else it reads like there is probably no difference.
In fact I don't think synchronization ever completes.

**Comment by jidanni** [comment]
OK, please add that to
```
Warning: package scrypt not available, using fallback
```
else it reads like there is probably no difference.
In fact I don't think synchronization ever completes.

**Comment by jidanni** [comment]
OK I found https://pypi.python.org/pypi/ltc_scrypt
Now I am going to figure out how to install it.

**Comment by jidanni** [comment]
Oh, I see
# aptitude install python3-scrypt

**Comment by jidanni** [comment]
OK, now no more 100% continual CPU use. But still transactions never get confirmed, always still "synchronizing" . #120.
