### ISSUE TITLE
Travis Ormandy vulnerability? Are we at risk. 

### ISSUE THREAD

**Issue by jpuk** [pooler/electrum-ltc#121]
Hello guys. 

I am sure by now you have seen the reports of the serious vulnerability in electrum for which a new version 3.0.4 has been released. 

Can you confirm if electrum ltc is also vulnerable and if so any roadmap towards fixing this issue?

https://t.co/HWyW556ORO

**Comment by jidanni** [comment]
https://github.com/spesmilo/electrum/issues/3374 direct link.

**Comment by pooler** [comment]
Electrum-LTC is certainly affected. And it seems pretty safe to say that every recent Electrum port/fork is.

I merged the 3.0.4 fix into master yesterday (e6030e3), shortly after it was merged upstream.

I'll try to make a new release with binaries soon, even if this is far from ideal timing.

**Comment by jpuk** [comment]
Great to hear you're already working on it.

Thank you very much.

**Comment by pooler** [comment]
Version 3.0.4.1 has just been released.

**Comment by dserodio** [comment]
Electrum 3.0.4 included only a partial fix, and 3.0.5 was released to fully address the issue. Does electrum-ltc 3.0.4.1 include the fix from Electrum 3.0.5 too?

**Comment by pooler** [comment]
@dserodio: Electrum-LTC 3.0.5.1 was released earlier today, check the website.
