### ISSUE TITLE
Electrum LTC not opening after 3.0.4.1 update on Mac Os

### ISSUE THREAD

**Issue by lorepieri8** [pooler/electrum-ltc#125]
I've updated electrum LTC to the latest version 3.0.4.1, but after the update I'm not able to access electrum LTC anymore. I run mac OS 10.9.4, the icon bounces on the lower bar and then disappear instead of opening the program.

I've made a backup of my old wallet file and all the .electrum-ltc folder, and of course of my seed.

I've tried to delete the old .electrum-ltc and install from scratch, but it doesn't work either.

Additional info: I managed to install an old version, 2.6.4.2 and it works fine. Still the issue remains, since there is vulnerability solved in 3.0.4.1 that I would like to cover.

**Comment by pooler** [comment]
Does Electrum (for Bitcoin) 3.0.5 work fine on this machine?
What year is your Mac? Do you know the model of the CPU?

**Comment by lorepieri8** [comment]
CPU is Intel Core i5, with 1,4 GHz. The model is from 2014.
Didn't tried Electrum BTC since I would like to first solve issues with the LTC one.

**Comment by pooler** [comment]
Do you get any particular errors in the console?
By the way, 3.0.5.1 has been released.

**Comment by lorepieri8** [comment]
I'm installing with simple drag and drop into the application folder. Then when I click on the icon, the program seems to launch for a split second, then disappear without any error. 
Is there a way to log the process in the console?
I will try with 3.0.5.1 and let you know, thanks for the support btw.

**Comment by pooler** [comment]
See here: https://support.omnigroup.com/console-osx/

**Comment by lorepieri8** [comment]
07/01/18 22:23:17,201 gkbisd[144]: Unable to collect cdhash for /Applications/Electrum-LTC.app (error code 100024)
07/01/18 22:23:17,998 com.apple.launchd.peruser.501[157]: (Electrum-LTC.76416[45568]) Exited with code: 255

**Comment by lorepieri8** [comment]
The 3.0.5 is not working either.

`air-di-lorenzo:~ lorenzo$ /Applications/Electrum-LTC.app/Contents/MacOS/Electrum-LTC -v
[SimpleConfig] electrum directory /Users/lorenzo/.electrum-ltc
[get_server] [Errno 61] Connection refused
[Plugins] registering hardware digitalbitbox: ('hardware', 'digitalbitbox', 'Digital Bitbox wallet')
[Plugins] registering hardware keepkey: ('hardware', 'keepkey', 'KeepKey wallet')
[Plugins] registering hardware ledger: ('hardware', 'ledger', 'Ledger wallet')
[Plugins] registering hardware trezor: ('hardware', 'trezor', 'TREZOR wallet')
[profiler] __init__ 0.0063
[Network] blockchains dict_keys([0])
[Network] starting network
[Network] connecting to e-2.claudiobox.com:50004:s as new interface
[e-1.claudiobox.com] cannot resolve hostname
[Network] downloading  https://electrum-ltc.org/blockchain_headers
[FxThread] using exchange BitcoinAverage
Traceback (most recent call last):
  File "electrum-ltc", line 377, in <module>
  File "site-packages/Electrum_LTC-3.0.5.1-py3.6.egg/electrum_ltc/daemon.py", line 302, in init_gui
  File "/Users/pooler/miniconda3/envs/electrum/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "site-packages/Electrum_LTC-3.0.5.1-py3.6.egg/electrum_ltc_gui/qt/__init__.py", line 35, in <module>
  File "/Users/pooler/miniconda3/envs/electrum/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 714, in load_module
ImportError: dlopen(/var/folders/f1/mytd0rsx76lbmj1fdgvwcp_40000gn/T/_MEIefLRKs/PyQt5.QtGui.so, 2): Symbol not found: _LSCopyDefaultApplicationURLForURL
  Referenced from: /var/folders/f1/mytd0rsx76lbmj1fdgvwcp_40000gn/T/_MEIefLRKs/QtCore
  Expected in: /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
 in /var/folders/f1/mytd0rsx76lbmj1fdgvwcp_40000gn/T/_MEIefLRKs/QtCore
[48383] Failed to execute script electrum-ltc
[Plugins] stopped
[Daemon] shutting down network
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)
[e-2.claudiobox.com] cannot resolve hostname
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)
[electrum-ltc.villocq.com] saving certificate
[electrum-ltc.villocq.com] connected
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)
[Network] stopping network
[Network] stopped
[Daemon] stopped
air-di-lorenzo:~ lorenzo$ 
`

**Comment by pooler** [comment]
Thank you, I have a better understanding of the issue now.

One more thing, could you please check whether Electrum (for Bitcoin) 3.0.5 runs into the same problem?

**Comment by lorepieri8** [comment]
It works!! Thank you for the support.

I didn't tried the BTC version though, hopefully it's solved even there.

**Comment by lorepieri8** [comment]
Ok, the error is there even for the BTC version, I will signal this on their repo.

**Comment by bauerj** [comment]
@pooler What did you do to solve this?

**Comment by pooler** [comment]
Apparently Qt 5.9 dropped support for OS X 10.9, so I made a new build with Qt 5.8.
