### ISSUE TITLE
Electrum updated to 3.0.5, 3.0.4 did not fix the vulnerability, please update the current electrum-ltc version

### ISSUE THREAD

**Issue by snitko** [pooler/electrum-ltc#126]
As stated in this tweet: https://twitter.com/ElectrumWallet/status/950163143082299392
New release: 3.0.5. (security update). https://electrum.org/#download  
Please upgrade; release 3.0.4 did not completely address the vulnerability.

**Comment by pooler** [comment]
Version 3.0.5.1 has just been released.
