### ISSUE TITLE
Is the verification OK 

### ISSUE THREAD

**Issue by emilio888** [pooler/electrum-ltc#129]
gpg: Signature made 01/08/18 03:33:39 Eastern Standard Time
gpg:                using RSA key CAE1092AD3553FFD21C05DE36FC4C9F7F1BE8FEA
gpg: Good signature from "pooler <pooler@litecoinpool.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: CAE1 092A D355 3FFD 21C0  5DE3 6FC4 C9F7 F1BE 8FEA

The RSA key is different from the one on the site of the instructions. Is that OK ?

Thanks

**Comment by pooler** [comment]
It's the same key, just formatted differently.
