### ISSUE TITLE
No module named 'httplib'

### ISSUE THREAD

**Issue by jonahar** [pooler/electrum-ltc#135]
When running electrum-ltc from the 3.0.5.1 tar release, an error occurs
`Error: No module named 'httplib'. Try 'sudo pip install <module-name>'`
I think this is the same issue as the following: [https://github.com/fyookball/electrum/issues/442](https://github.com/fyookball/electrum/issues/442)

**Comment by pooler** [comment]
It doesn't appear to be the same issue, as the Electrum-LTC 3.0.5.1 tarball does include the `packages` directory.
What OS/distro/version are you using, and what commands did you issue?

**Comment by jonahar** [comment]
Ubuntu 16.04. I simply run 'electrum-ltc' from the top directory

**Comment by pooler** [comment]
I am unable to reproduce on a fresh install of Ubuntu 16.04.

**Comment by jonahar** [comment]
This is the tar I used [https://github.com/pooler/electrum-ltc/archive/3.0.5.1.tar.gz](https://github.com/pooler/electrum-ltc/archive/3.0.5.1.tar.gz)

**Comment by pooler** [comment]
That is a tarball of the git repo, not the release tarball. Please use the tarball from the website.

**Comment by jonahar** [comment]
Thanks. I thought the tarball on the release page on github is already built.
