### ISSUE TITLE
Error 1 on install

### ISSUE THREAD

**Issue by fsantiago07044** [pooler/electrum-ltc#137]
Fedora 27

pip3 install https://electrum-ltc.org/download/Electrum-LTC-3.0.5.1.tar.gz
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting https://electrum-ltc.org/download/Electrum-LTC-3.0.5.1.tar.gz
  Using cached https://electrum-ltc.org/download/Electrum-LTC-3.0.5.1.tar.gz
Requirement already satisfied: pyaes>=0.1a1 in /usr/local/lib/python3.6/site-packages (from Electrum-LTC==3.0.5.1)
Requirement already satisfied: ecdsa>=0.9 in /usr/local/lib/python3.6/site-packages (from Electrum-LTC==3.0.5.1)
Requirement already satisfied: pbkdf2 in /usr/local/lib/python3.6/site-packages (from Electrum-LTC==3.0.5.1)
Requirement already satisfied: requests in /usr/lib/python3.6/site-packages (from Electrum-LTC==3.0.5.1)
Requirement already satisfied: qrcode in /usr/local/lib/python3.6/site-packages (from Electrum-LTC==3.0.5.1)
Collecting scrypt>=0.6.0 (from Electrum-LTC==3.0.5.1)
  Using cached scrypt-0.8.0.tar.gz
Requirement already satisfied: protobuf in /usr/local/lib64/python3.6/site-packages (from Electrum-LTC==3.0.5.1)
Requirement already satisfied: dnspython in /usr/local/lib/python3.6/site-packages (from Electrum-LTC==3.0.5.1)
Requirement already satisfied: jsonrpclib-pelix in /usr/local/lib/python3.6/site-packages (from Electrum-LTC==3.0.5.1)
Requirement already satisfied: PySocks>=1.6.6 in /usr/lib/python3.6/site-packages (from Electrum-LTC==3.0.5.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.6/site-packages (from requests->Electrum-LTC==3.0.5.1)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/lib/python3.6/site-packages (from requests->Electrum-LTC==3.0.5.1)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/lib/python3.6/site-packages (from requests->Electrum-LTC==3.0.5.1)
Requirement already satisfied: six in /usr/lib/python3.6/site-packages (from qrcode->Electrum-LTC==3.0.5.1)
Requirement already satisfied: setuptools in /usr/lib/python3.6/site-packages (from protobuf->Electrum-LTC==3.0.5.1)
Installing collected packages: scrypt, Electrum-LTC
  Running setup.py install for scrypt ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-mkmrqan4/scrypt/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-01zwgykj-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    copying scrypt.py -> build/lib.linux-x86_64-3.6
    running build_ext
    building '_scrypt' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    creating build/temp.linux-x86_64-3.6/scrypt-1.2.0
    creating build/temp.linux-x86_64-3.6/scrypt-1.2.0/lib
    creating build/temp.linux-x86_64-3.6/scrypt-1.2.0/lib/crypto
    creating build/temp.linux-x86_64-3.6/scrypt-1.2.0/lib/scryptenc    creating build/temp.linux-x86_64-3.6/scrypt-1.2.0/lib/util
    creating build/temp.linux-x86_64-3.6/scrypt-1.2.0/libcperciva
    creating build/temp.linux-x86_64-3.6/scrypt-1.2.0/libcperciva/alg
    creating build/temp.linux-x86_64-3.6/scrypt-1.2.0/libcperciva/crypto
    creating build/temp.linux-x86_64-3.6/scrypt-1.2.0/libcperciva/util
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DHAVE_CONFIG_H -DHAVE_CLOCK_GETTIME=1 -DHAVE_LIBRT=1 -DHAVE_POSIX_MEMALIGN=1 -DHAVE_STRUCT_SYSINFO=1 -DHAVE_STRUCT_SYSINFO_MEM_UNIT=1 -DHAVE_STRUCT_SYSINFO_TOTALRAM=1 -DHAVE_SYSINFO=1 -DHAVE_SYS_SYSINFO_H=1 -D_FILE_OFFSET_BITS=64 -Iscrypt-1.2.0 -Iscrypt-1.2.0/lib -Iscrypt-1.2.0/lib/scryptenc -Iscrypt-1.2.0/lib/crypto -Iscrypt-1.2.0/lib/util -Iscrypt-1.2.0/libcperciva/cpusupport -Iscrypt-1.2.0/libcperciva/alg -Iscrypt-1.2.0/libcperciva/util -Iscrypt-1.2.0/libcperciva/crypto -I/usr/include/python3.6m -c src/scrypt.c -o build/temp.linux-x86_64-3.6/src/scrypt.o -O2
    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-mkmrqan4/scrypt/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-01zwgykj-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-mkmrqan4/scrypt/

Anything I can do?

**Comment by pooler** [comment]
Try this: `sudo dnf install redhat-rpm-config`

**Comment by fsantiago07044** [comment]
On January 14, 2018 4:24:56 PM EST, pooler <notifications@github.com> wrote:
>Try this: `sudo dnf install redhat-rpm-config`

Different error now: (but thank you)

pip3 install https://electrum-ltc.org/download/Electrum-LTC-3.0.5.1.tar.gz
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting https://electrum-ltc.org/download/Electrum-LTC-3.0.5.1.tar.gz
  Using cached https://electrum-ltc.org/download/Electrum-LTC-3.0.5.1.tar.gz
Requirement already satisfied: pyaes>=0.1a1 in /usr/local/lib/python3.6/site-packages (from Electrum-LTC==3.0.5.1)
Requirement already satisfied: ecdsa>=0.9 in /usr/local/lib/python3.6/site-packages (from Electrum-LTC==3.0.5.1)
Requirement already satisfied: pbkdf2 in /usr/local/lib/python3.6/site-packages (from Electrum-LTC==3.0.5.1)
Requirement already satisfied: requests in /usr/lib/python3.6/site-packages (from Electrum-LTC==3.0.5.1)
Requirement already satisfied: qrcode in /usr/local/lib/python3.6/site-packages (from Electrum-LTC==3.0.5.1)
Collecting scrypt>=0.6.0 (from Electrum-LTC==3.0.5.1)
  Using cached scrypt-0.8.0.tar.gz
Requirement already satisfied: protobuf in /usr/local/lib64/python3.6/site-packages (from Electrum-LTC==3.0.5.1)
Requirement already satisfied: dnspython in /usr/local/lib/python3.6/site-packages (from Electrum-LTC==3.0.5.1)
Requirement already satisfied: jsonrpclib-pelix in /usr/local/lib/python3.6/site-packages (from Electrum-LTC==3.0.5.1)
Requirement already satisfied: PySocks>=1.6.6 in /usr/lib/python3.6/site-packages (from Electrum-LTC==3.0.5.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.6/site-packages (from requests->Electrum-LTC==3.0.5.1)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/lib/python3.6/site-packages (from requests->Electrum-LTC==3.0.5.1)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/lib/python3.6/site-packages (from requests->Electrum-LTC==3.0.5.1)
Requirement already satisfied: six in /usr/lib/python3.6/site-packages (from qrcode->Electrum-LTC==3.0.5.1)
Requirement already satisfied: setuptools in /usr/lib/python3.6/site-packages (from protobuf->Electrum-LTC==3.0.5.1)
Installing collected packages: scrypt, Electrum-LTC
  Running setup.py install for scrypt ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-otib7rxi/scrypt/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-211yugjo-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    copying scrypt.py -> build/lib.linux-x86_64-3.6
    running build_ext
    building '_scrypt' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    creating build/temp.linux-x86_64-3.6/scrypt-1.2.0
    creating build/temp.linux-x86_64-3.6/scrypt-1.2.0/lib
    creating build/temp.linux-x86_64-3.6/scrypt-1.2.0/lib/crypto
    creating build/temp.linux-x86_64-3.6/scrypt-1.2.0/lib/scryptenc    creating build/temp.linux-x86_64-3.6/scrypt-1.2.0/lib/util
    creating build/temp.linux-x86_64-3.6/scrypt-1.2.0/libcperciva
    creating build/temp.linux-x86_64-3.6/scrypt-1.2.0/libcperciva/alg
    creating build/temp.linux-x86_64-3.6/scrypt-1.2.0/libcperciva/crypto
    creating build/temp.linux-x86_64-3.6/scrypt-1.2.0/libcperciva/util
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DHAVE_CONFIG_H -DHAVE_CLOCK_GETTIME=1 -DHAVE_LIBRT=1 -DHAVE_POSIX_MEMALIGN=1 -DHAVE_STRUCT_SYSINFO=1 -DHAVE_STRUCT_SYSINFO_MEM_UNIT=1 -DHAVE_STRUCT_SYSINFO_TOTALRAM=1 -DHAVE_SYSINFO=1 -DHAVE_SYS_SYSINFO_H=1 -D_FILE_OFFSET_BITS=64 -Iscrypt-1.2.0 -Iscrypt-1.2.0/lib -Iscrypt-1.2.0/lib/scryptenc -Iscrypt-1.2.0/lib/crypto -Iscrypt-1.2.0/lib/util -Iscrypt-1.2.0/libcperciva/cpusupport -Iscrypt-1.2.0/libcperciva/alg -Iscrypt-1.2.0/libcperciva/util -Iscrypt-1.2.0/libcperciva/crypto -I/usr/include/python3.6m -c src/scrypt.c -o build/temp.linux-x86_64-3.6/src/scrypt.o -O2
    src/scrypt.c:27:10: fatal error: Python.h: No such file or directory
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-otib7rxi/scrypt/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-211yugjo-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-otib7rxi/scrypt/
--

Thanks,

Fabian S.

OpenPGP: 3C3FA072ACCB7AC5DB0F723455502B0EEB9070FC

**Comment by fsantiago07044** [comment]
On January 14, 2018 4:24:56 PM EST, pooler <notifications@github.com> wrote:
>Try this: `sudo dnf install redhat-rpm-config`

So i gather it's failing on install of scrypt. Not sure how to fix that. 
--

Thanks,

Fabian S.

OpenPGP: 3C3FA072ACCB7AC5DB0F723455502B0EEB9070FC

**Comment by fsantiago07044** [comment]
Scrypt installs fine with pip, just fails under pip3 when installing electrum.

**Comment by pooler** [comment]
>  src/scrypt.c:27:10: fatal error: Python.h: No such file or directory

`sudo dnf install python3-devel`

**Comment by fsantiago07044** [comment]
On January 15, 2018 3:20:58 AM EST, pooler <notifications@github.com> wrote:
>>  src/scrypt.c:27:10: fatal error: Python.h: No such file or directory
>
>`sudo dnf install python3-devel`

That was it. Thanks. Case closed. 
--

Thanks,

Fabian S.

OpenPGP: 3C3FA072ACCB7AC5DB0F723455502B0EEB9070FC
