### ISSUE TITLE
Executable doesn't shut down after quitting

### ISSUE THREAD

**Issue by Hub-O-Gits** [pooler/electrum-ltc#141]
Electrum-LTC: Windows portable v3.0.5.1
Platform: Windows 7 x64 SP1
Conditions: Usually this occurs after Electrum-LTC has been running for awhile, or after some basic operation has been performed - like sending some LTC to another address.

After selecting File > Quit, the GUI closes but electrum-ltc-3.0.5.1-portable.exe remains in memory, and the process has to be ended manually from the Task Manager.

**Comment by pooler** [comment]
Can you reproduce this issue with version 3.1.2.1?

**Comment by Hub-O-Gits** [comment]
On initial testing, no; it doesn't seem to happen anymore.
I'll know better the next time I have a LTC transaction to perform.

**Comment by Hub-O-Gits** [comment]
I've since updated to v3.1.3.1, have performed several send & receive LTC transactions, and can confirm that the processes terminate when the program is exited.
