### ISSUE TITLE
Unable to build for MacOS

### ISSUE THREAD

**Issue by nitinsurana** [pooler/electrum-ltc#142]
Hi

I'm trying to build for macOS. The readme refers to a file `setup-release.py` for macOS build, but there's no such file.

Is the file supposed to be generated somehow ?

**Comment by sunk818** [comment]
You don't want to just download the wallet?

**Comment by nitinsurana** [comment]
I want to contribute hence need to know how to compile the sources.

**Comment by pooler** [comment]
The readme should be updated (upstream; feel free to open a ticket there). PyInstaller is now used instead of py2app to build macOS binaries, see `contrib/make_osx`.

> I want to contribute hence need to know how to compile the sources.

Not necessarily. Electrum is written in Python, so you can simply run it from source.

**Comment by nitinsurana** [comment]
@pooler thanks for replying. Unfortunately, the readme isn't updated upstream and that's the reason, I came downstream :-P
It'll be great if you can share a script or set of commands which could used to build the executable on macOS nowadays.

**Comment by pooler** [comment]
The script and the instructions have been updated.
