### ISSUE TITLE
Missed address and missed LTC from wallet!

### ISSUE THREAD

**Issue by mahdiyari** [pooler/electrum-ltc#143]
Hello,
I missed one address from my wallet which has 0.57 LTC!
it happened in opening wallet after installing new windows (changing win 7 to win 10)
I tried with some other versions and now I'm on last version.
also, tried with seed words!
I don't know what happened to that address.
also, it was not my last transaction to that address.
missed address: LZnG4ofXgzMaVVErZtNVm92ZKVBQqvUruj

I tried by sending some LTC to that address.
anyway, no chance to get that LTC back.

**Comment by pooler** [comment]
First of all, are you 100% sure that the address in question was generated as part of *that* wallet?

Was this an imported address? Electrum generates addresses deterministically, so it's not possible that an address cannot be restored from its original seed.

What version of Electrum-LTC were you using when this wallet was first created? About how many transactions has the wallet seen, in total? Did you ever change the gap limit?

**Comment by mahdiyari** [comment]
Yeah, I know it is impossible! but, it has happened.
I generated my wallet on version 2.9.3.1 then updated to the last version when announced there is a bug.
my wallet was encrypted by strong password.
yes, I'm sure that address generated by electrum. I found this address by following my first transaction to the wallet.
you can start from this address: 2.92 LTC was in `LhhGErQCRyB1yfWdNN9T9Crz61bJnjstFC`
let's follow transactions: send 0.4 LTC to `LeSzCDzkqwzzskVg82E2jspsWMHQuV8WM4`
then 0.4 LTC send to LNL4gUHZdSgGCF7wXgMkqDZtqwFuExCXMJ
and 1.2 LTC send to LiE1cwNaZ541z7KpFsrHoK7gCpcZpW95h2

All destination addresses are exchanges! I can't find that transactions in the restored wallet. (even in backup wallet file)
after the last transaction (1.2 LTC) I should have 0.57 LTC in LZnG4ofXgzMaVVErZtNVm92ZKVBQqvUruj

and no, I don't change the gap. right now, I have 26 address in my wallet.

**Comment by pooler** [comment]
Sorry, I don't understand. Are you saying that you found the address by following a chain of transactions on a block explorer? I'm probably missing something here, but what exactly indicates that the final address is yours?

**Comment by cavapoo2** [comment]
0.57 ( sent to LZnG4ofXgzMaVVErZtNVm92ZKVBQqvUruj ) is unspent you should still have it. Its your change address after sending 1.2 to LiE1cwNaZ541z7KpFsrHoK7gCpcZpW95h2.  

https://live.blockcypher.com/ltc/tx/425fd26732e5d01c8165d38a06f42a96da6ae2d3c0bcdf4cd6694ce30db08a87/

**Comment by mahdiyari** [comment]
@pooler 
after restoring my wallet, I understand I don't have some LTC. so I found my LTC address on block explorer.
@cavapoo2 Yeah. but, I don't have!
I tried 3 different version of electrum with my seed words and wallet file.
can I use electrum seed in other wallets?

**Comment by mahdiyari** [comment]
Finally, I got all of my LTC.
It happened after opening my wallet again. I don't know why now my wallet synced and recently it was not fully synced even after restoring by seed.
anyway, Thanks for your time.
