### ISSUE TITLE
Updated to 3.0.6.2 but still hangs on Mac

### ISSUE THREAD

**Issue by pingram3541** [pooler/electrum-ltc#150]
Same issue as with previous version, every time I open and enter my password the app hangs for 10-15min and spikes my CPU.

Then once the wallet is displayed, within moments as the new transactions show up as expected but when I go to add a descriptive label to the each new transaction, the first attempt also always locks up the app for another 10-15min and from then on out everything is snappy...until I close the app, it closes the UI but the app still sits in my dock for about 10-15min unless I force close it.

**Comment by pooler** [comment]
Is this with the official binary, or running from source? What version of macOS?

**Comment by sunk818** [comment]
I'm using macOS 10.12.6 and this doesn't happen to me. You might try a clean uninstall and re-install.

**Comment by pingram3541** [comment]
Official dmg from website, macOS 10.12.6 high sierra, gonna try a clean install.

**Comment by pingram3541** [comment]
Nope, removed all files from ~/.electrum-ltc folder except my wallet file and same result.

**Comment by SomberNight** [comment]
How big is this wallet? (wallet file size, ~num transactions, ~num addresses)

**Comment by pingram3541** [comment]
The wallet file size is 10.1MB and the num transactions is 140, number of addresses is 40

**Comment by SomberNight** [comment]
Maybe https://github.com/spesmilo/electrum/issues/3778 ?

In the in-app QT console (`Console` tab inside GUI), what does
```
bitcoin.AES
```
print?

And if nothing, what does
```
bitcoin.AES is None
```
print?

**Comment by pingram3541** [comment]
`bitcoin.AES is None`
True

**Comment by SomberNight** [comment]
That means pycryptodomex is not present so it fails back to using pyaes,
You could try installing pycryptodomex yourself, see if that works.

**Comment by pingram3541** [comment]
pycryptodomex, hmm that just leads me down a rabbit hole installing tons of python s/w and dev tools on my mac.  Gonna spin this up on a linux box and see if I get the same experience.

IMO, all needed libs should be self-contained in the binary.  No one wants to hack their puter just to install a wallet.

**Comment by pooler** [comment]
@pingram3541, could you please test [this new build](https://electrum-ltc.org/download/electrum-ltc-3.0.6.2-1.dmg) of 3.0.6.2?

**Comment by pingram3541** [comment]
Ok, still got the spinner for about a minute but that works much faster now!

Here is what I did.

1) Removed all but /wallets folder from ~/.electrum-ltc
2) Renamed old app file w/ version
3) Installed new app and rename w/ version
4) Went through first time setup and opened old wallet file

All transactions show with a status of unverified and have no date otherwise all is good.  The server setup is auto and I show 10 nodes currently connected.

**Comment by pingram3541** [comment]
Leaving the wallet open for a while, dates and verified status now show properly.  Thx for the fix
