### ISSUE TITLE
Wrong generated Addresses

### ISSUE THREAD

**Issue by robthepop** [pooler/electrum-ltc#152]
Hello,

I used the portable and the windows installer version 3.0.6.2. Both with legacy and segwit. I tried it very often in the past days. In every case the client generated addresses that are starting "ltc1q". 

Is this a bug, because those addresses are not working?!

Thank you

**Comment by MrMebelMan** [comment]
I have the same issue on Win7, Win8, Linux Mint and Linux Debian. But only with "segwit" wallets. It generates invalid addresses starting with "ltc". If I use the command line to create more addresses, it does the same.

**Comment by pooler** [comment]
It is correct for Segwit wallets to generate addresses starting with `ltc1`. This message is displayed every time you create a new wallet, when you have to choose between Standard and Segwit:

> The type of addresses used by your wallet will depend on your seed. Segwit wallets use bech32 addresses, defined in BIP173. Please note that websites and other wallets may not support these addresses yet. Thus, you might want to keep using a non-segwit wallet in order to be able to receive litecoins during the transition period.

@robthepop: if you mean that you get addresses starting with `ltc1` in a Standard wallet, could you please describe how you created the wallet, step by step?

**Comment by pooler** [comment]
No response, closing.
