### ISSUE TITLE
Electrum LTC crashes on right-click "edit label" mac OS

### ISSUE THREAD

**Issue by goodc0re** [pooler/electrum-ltc#153]
Electrum LTC (latest version) crashes on right-click "edit label" mac OS (latest version). 

By right clicking on the label column of any given address on the Addresses screen, the program crashes, every time.

**Comment by pooler** [comment]
It appears to be a bug in the Qt library.

Could you please test [this new build](https://electrum-ltc.org/download/electrum-ltc-3.0.6.2-2.dmg) of 3.0.6.2?
