### ISSUE TITLE
Hack?

### ISSUE THREAD

**Issue by benahavis** [pooler/electrum-ltc#158]
I sent 15 LTC to a new electrum-ltc wallet yesterday at 17.48 and found that they have been sent to another wallet at 21.44. How?

**Comment by raymondcarl** [comment]
Can you post which website you downloaded Electrum-LTC from, the file name, OS, etc.?  I think there are a lot of malicious versions floating around if you don't get the legitimate version and verify the signatures.

**Comment by benahavis** [comment]
I am operating on windows10. Electrum-ltc 3.0.6.2, downloaded from electrum-ltc.org with filename electrum-ltc-3.0.6.2-setup. (13MB)

**Comment by pooler** [comment]
Could you provide a transaction ID?
Can you compute the SHA-256 hash of the file you downloaded?

One possibility is that your computer was compromised and an attacker gained access to your wallet.

**Comment by benahavis** [comment]
Transaccion ID : 1b9582e59c6afbfb8ea461b437392c27f2f6680a3b0dbf41e60191736a5d07c9
I don't know where to find the SHA-256 hash

**Comment by pooler** [comment]
[Here](https://superuser.com/a/898377) is a way to compute the hash.

**Comment by benahavis** [comment]
Got this : SHA_1  C91A5DE078CDA5C89ADF4E7F76A476CA57057A65

**Comment by benahavis** [comment]
SHA-256 : D87A73CE015DED1FD6220C0B5CAB959A65BB5DD7652B7CB6FFXD9DC00E60A8875

**Comment by pooler** [comment]
The hashes match, so the file should be good.

I'm afraid the most probable explanation for what happened is that your computer was compromised in some way.

**Comment by benahavis** [comment]
I checked the address of the wallet it was sent to, and the LTC are still there.
Is there any way to block such an account?

**Comment by benahavis** [comment]
I am also certain it wasn't a computer hack. Something else must have happened

**Comment by pooler** [comment]
> I checked the address of the wallet it was sent to, and the LTC are still there.
> Is there any way to block such an account?

I'm afraid not.

> I am also certain it wasn't a computer hack. Something else must have happened

What makes you certain?

**Comment by benahavis** [comment]
The computer wasn't on at the time of the transaccion.
Also found this about a loafwallet user, same wallet it went to.
As captioned, please help. I had trouble sending out LTC from loafwallet to the exchange yesterday. So I deleted the loafwallet app and downloaded and reinstalled. After I reintalled Loafwallet and did the recovery of my wallet, my balance became zero.
Loafwallet history shows a transaction to an address which I don’t know. I did not submit any withdrawal.
The transaction number is debf5c1071a8c7b7e2fa3067a09047da70bfa12022a69fbe06d1bf5eed14dff0
The receive address is
LLAAnNCrDiAhUcPc9iVCx5obDmq11sxSTR
Is there anyway to stop the transaction to recover my coins? Does it mean that they are stolen? Please help. I am panicking.

**Comment by pooler** [comment]
> The computer wasn't on at the time of the transaccion.

That doesn't matter. The attacker could have stolen your wallet data earlier, and then transferred the coins using any computer.

> Is there anyway to stop the transaction to recover my coins?

I'm sorry, but confirmed transactions cannot be reverted.

**Comment by raymondcarl** [comment]
@benahavis 

Could you just explain more clearly what happened in your case?  The story you quoted Loafwallet sounds much more likely to be either a user issue or a malicious version of Loaf floating around on the Android or App store.

In your case, it's confusing to follow what exactly happened.  You sent 15 LTC from an exchange to your Electrum wallet.  Did the LTC ever arrive at your electrum wallet address?  

If would probably be best to start from the time you downloaded Electrum, when did you set a password on the wallet, when you sent LTC to Electrum, what time it arrived, what time it left.

**Comment by benahavis** [comment]
Hi,
Because of the LTC hard fork, I got the advise to use a new wallet and leave the original empty to avoid scams.
So I downloaded and installed the electrum-LTC wallet at 17.00, wrote down the seed, set a strong password, and sent the LTC there at 17.48. The transaccion was almost immediate and the LTC were received on the electrum wallet. I was out for most of the evening and when I looked in the morning a transaccion had been done at 21.44, transferring all to this unknown wallet (LLAAnNCrDiAhUcPc9iVCx5obDmq11sxSTR).
That is all that happened.
Regards

**Comment by raymondcarl** [comment]
The first part is strange.  If you don't care about "claiming" Litecoin Cash, there's no reason to transfer your LTC to any wallet.  You would only do that if you have LTC today, and you want to also claim Litecoin Cash.  And more specifically, you would only do that if your current LTC holdings are stored somewhere that will not a) give you access to your private key, or b) won't do the work on their end to "claim" the Litecoin Cash for you.  So, it's really strange you got that advice because the real scam comes from convincing people to do what you did and put their seed or private key into a malicious wallet.  Did you put anything in a new wallet other than the Electrum wallet?

**Comment by benahavis** [comment]
I had 15 LTC which I transferred from the coinbase wallet to the electrum
one to claim the LCC, I wanted to get the litecoin cash.
The advice came from BTCdirect which is a reference. They never advised me
to open an electrum wallet but it seemed reliable, now you are saying it is
a malicious wallet. The SHA-256 hash was correct, so...
It is the only wallet I have used outside coinbase and the nano ledger
hardware one.


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-02-24 21:46 GMT+01:00 Raymond Carl <notifications@github.com>:

**Comment by raymondcarl** [comment]
Sorry, what I have been trying to say is that you may have downloaded a malicious Litecoin **Cash** Wallet?  Yes, you are correct that the Electrum LTC wallet you downloaded seems to be OK as indicated by the correct hash.  The vulnerability I've been trying to ask about is the Litecoin Cash wallet you downloaded.  Did you put your **Litecoin** wallet seed into the **Litecoin cash** wallet?

**Comment by raymondcarl** [comment]
@pooler   Might be OK to close this one out?  Given what I saw the whole Litecoin Cash episode, there could've been #1: malicious version of Litecoin Cash where the user inputs their HD mnemonic phrase, which is then forwarded onwards to the creator, #2: malicious code on user's PC.  #3: vulnerability in the Electrum wallet, but would be impossible to confirm with info given above, would most likely affect all branches of Electrum wallet, and least like to be the case of the 3 scenarios above.
