### ISSUE TITLE
Trezor based Sign Message produces bad signature

### ISSUE THREAD

**Issue by MarvinOl** [pooler/electrum-ltc#16]
First thanks for Trezor support!

Using master branch from yesterday. Going into Sign/verify Message everything works as it does with Bitcoin Electrum - asks approval on Trezor screen, asks for pin, signs on Trezor and displays the result in the Signature field. But this signature is not correct. Even clicking Verify in the same windows says that the signature is invalid! Tested the signature with the official litecoin client and it is not correct.

**Comment by prusnak** [comment]
I recommend changing the magic to "Bitcoin Signed Message" here:
https://github.com/pooler/electrum-ltc/blob/v1.9.8.4/lib/bitcoin.py#L351
This is a very poor decision to break things appart for no obvious reason.

**Comment by pooler** [comment]
@prusnak: Litecoin Core has been using the magic string "Litecoin Signed Message" since 2011. What you are proposing would break compatibility with all other Litecoin clients, which is highly undesirable.

**Comment by prusnak** [comment]
That is indeed very unfortunate ... I'll reopen the trezor-mcu issue.

**Comment by prusnak** [comment]
Fixed in TREZOR firmware 1.3.6

**Comment by pooler** [comment]
@prusnak Thank you!

**Comment by prusnak** [comment]
See https://github.com/pooler/electrum-ltc/issues/34 though.
