### ISSUE TITLE
LTC Wallet Funds are missing 

### ISSUE THREAD

**Issue by TCHAP424** [pooler/electrum-ltc#160]
Im trying to understand why my coins are not in my wallet. 
The bottom tab is showing that I have 1.051393 LTC in my wallet but on the address tab it is only showing I have 0.866006 in wallet LWcahnQzy54BEqY4rWJ5tV7jL6f2eJSb4C. 
I just transfered that amont from that ammount from wallet LazJKfXMYNRG5NPsK7u7CJxWq6t5L7noBG.

Before I made the transfer there was .185761 LTC shown here in a screen shot from yesterday.
<img width="1680" alt="screen shot 2018-03-03 at 5 16 21 pm" src="https://user-images.githubusercontent.com/37051878/36952442-cdfb7762-1fd5-11e8-8d0f-812e1e29532b.png">
<img width="1680" alt="screen shot 2018-03-03 at 5 16 32 pm" src="https://user-images.githubusercontent.com/37051878/36952461-f8942a96-1fd5-11e8-8d93-f26fccfb1c7f.png">
<img width="1680" alt="screen shot 2018-03-03 at 5 16 03 pm" src="https://user-images.githubusercontent.com/37051878/36952466-09a14c24-1fd6-11e8-800d-4c15b2bf4a30.png">

What happned to my .185761 LTC????

**Comment by pooler** [comment]
You only provided a screenshot of your receiving addresses. Check your change addresses as well.

**Comment by TCHAP424** [comment]
@pooler 
Change addresses?

**Comment by TCHAP424** [comment]
I found it. Thanks alot
