### ISSUE TITLE
Can't send LTC to addresses starting with 3 (Invalid Lines found)

### ISSUE THREAD

**Issue by Tube-jr** [pooler/electrum-ltc#166]
Hello,
everytime I try to send LTC to an address starting with 3, I get an error that says "Invalid lines found, line #1 (LTC address starting with 3)". Sending transaction to addresses starting with a L are no problem.

electrum-ltc 3.0.6.2

**Comment by pooler** [comment]
Recent versions of Electrum-LTC no longer support legacy P2SH addresses. You can convert them to the new format (which starts with 'M') using this utility: https://litecoin-project.github.io/p2sh-convert/

**Comment by Tube-jr** [comment]
Ah okay, thank you for your answer.
