### ISSUE TITLE
Version 3.1.0 - says mBTC instead of LTC, can't change in settings

### ISSUE THREAD

**Issue by aartiana** [pooler/electrum-ltc#167]
Interestingly, the website itself says Version 3.0.6.2 for all Windows versions :-) http://electrum-ltc.org
So, even though I see some issues may have been fixed with Version 3.1.1 here on this thread https://github.com/pooler/electrum-ltc/blob/master/RELEASE-NOTES - I don't know how to get the newest version.  (I downloaded the first option if that makes a difference).

I scrubbed the internet to discover the issue I was encountering to no avail.  When I recently activated the Electrum LTC wallet, I was going to transfer my Litecoin purchase from Coinbase (then through Coinbase's GDax.com to save fees which I saw on YouTube), and then into this wallet.  But, I noticed the currency setting was set for mBTC (micro-Bitcoin) rather than LTC (Litecoin) and I know you cannot mix multiple currencies or you lose it all!!  So I went to settings, but there was no setting for LTC!  It took me watching an older Youtube Video on Electrum LTC to see that THEIR older version Electrum LTC wallet actually said LTC.  So I know something happened but I don't know how to correct it on my own.  After finding the above-mentioned release notes searching for bugs, I figured this just needs to be addressed, and thus this bug report.  Thank you all for your time and attention! :-)

**Comment by pooler** [comment]
The latest released version of Electrum-LTC is 3.0.6.2, as stated on the website. You should use either that or git master, or wait for the next release.

The release notes are for upstream Electrum, on which Electrum-LTC is based. A versions based on 3.1.x has simply not been released yet.

**Comment by aartiana** [comment]
Thanks Pooler! So, I re-downloaded 3.0.6.2 and it at least shows "LTC" in the wallet.  I uninstalled the prior one and after looking around more online, decided to download the first .exe file to a flash drive, and it set up well.

Now, I am attempting to use the Receiving Address function to withdrawal my Litecoin that is currently in my Gdax.com account and send it to my Electrum LTC Wallet.

The receiving addresses that are generated all start with an "L" which I learned is an old format, and that Litecoin Addresses now need to begin with an "M."  

While they have a workaround set up within GDax system (done with coinbase.com/addresses if curious, which generated its own M-starting Litecoin address), I still cannot create a new-M-format receiving address for the actual withdrawal procedure.

Now, Gdax tech support suggested creating a new LTC receiving address here https://litecoin-project.github.io/p2sh-convert/ - but, each receiving address generated in my Electrum LTC wallet won't generate the new format at all, literally saying "please enter a valid address."

Is a new Electrum LTC wallet version forthcoming in the next few days or so, that would generate the "M" new format LTC receiving addresses by chance?  If not, might you know a better workaround?  I have diligently looked for solutions.  Thanks so much for your time and expertise!
