### ISSUE TITLE
Whole Wallet Emptied To an address

### ISSUE THREAD

**Issue by wtfhappened** [pooler/electrum-ltc#169]
I login to my wallet after 20 days As I wasn't able to access it on a business trip. The whole wallet I had full is gone. I keep my seed secure as well as my password. Not sure what exactly could have happened? Could this have been a bug? I was not near the computer where it was stored.........

Any help is appreciated. Thanks

![idk](https://user-images.githubusercontent.com/37744916/37865989-60b633d8-2f41-11e8-9907-7b8fb2a66184.jpg)

**Comment by raymondcarl** [comment]
Hi,

The first step in these cases should be to post which Operating System you're using, which version of the wallet you are using, and where did you download the wallet from.  And in this case, it seems odd that you 234 litecoin was payed out but you continue to receive litecoin from someone days after even though you were on a business trip?  Can you look at that transaction and see what address it went to, did you make any payments, etc.?

**Comment by raymondcarl** [comment]
@pooler Possibly a similar story, but haven't heard anything back in 1 month.  Close it out?
