### ISSUE TITLE
Not showing balance after Windows 10 Reset

### ISSUE THREAD

**Issue by lucellent** [pooler/electrum-ltc#172]
I recently reset (reinstalled/refreshed) my PC without deleting my files but Electrum got uninstalled. When I reinstalled it, I created a new wallet, used my previous seed so I could use the same wallet again. There, before the reset, I had about 5$ worth of LTC. After the reset, it shows that my balance is zero. I'm using the latest version.

**Comment by pooler** [comment]
By latest version do you mean 3.1.2.1?
Is any history at all being displayed?
Did you wait for Electrum-LTC to synchronize? Maybe post a screenshot of the network dialog (Tools > Network).

**Comment by lucellent** [comment]
Nope, no histories at all. Here's a screenshot http://prntscr.com/j2fpas

**Comment by pooler** [comment]
That is Electrum, not Electrum-LTC.

**Comment by lucellent** [comment]
Oh wow, why does it have to be so complicated :D 
Anyway, I downloaded the LTC version and everything is fine, thanks for clarifying.
