### ISSUE TITLE
I compiled for PRUX-ELECTRUM but shows error

### ISSUE THREAD

**Issue by BITRY** [pooler/electrum-ltc#173]
Hi there sorry maybe iam worn here to write that but i need help.

I have do successful all changes to connect with your Electrum-cli now (for PRUX) to my PRUX-ELECTRUM server. It already connected and everything ok. I do change all things to addrtyp=55 for P PRUX, an set connection to running PRUX-ELECTRUMSERVER. I do also a tx to pruxelectrums wallet, ok success, and think ah cool it works... 

But when i will send from my prux-electrum back,  i got this Message 

"   exceptions must be old-style classes or derived from BaseException, not NoneType  "

Can help me please, where to change, maybe you are interested to help bring out the fastest ELECTRUM_PRUX, i need really help with it. PRUX has a 3 sec Blocktarget so it is not easy, but i think if it works that would be nice for the market.

**Comment by pooler** [comment]
Off-topic.
