### ISSUE TITLE
Money stolen from electrum LTC wallet

### ISSUE THREAD

**Issue by Harryhobbit** [pooler/electrum-ltc#174]
so Im VERY new to this ltc and electrum and all of it. I have windows 10 and Electrum LTC 3.0.6.2. When I downloaded the wallet at first it showed some transactions, so i closed it deleted it and re downloaded it. The transactions where still there but no password on the acct and the balance was 0. deleted, re downloaded again, and transactions were not there. Set my password, then eventually moved money my wallet, then 5 minutes it was gone. Have no idea where it went. or how. Not sure what other info to post, or what to do. can someone please help me. I think they gave me someone elses wallet or something. but no matter how many times I delete it and re download it gives me the same thing. got it from electrum-ltc.org

**Comment by Harryhobbit** [comment]
just found the update of 3.1.2.1

**Comment by Harryhobbit** [comment]
ohk, I OBVIOUSLY should not have even tried this without more research. I tried checking signature, but cant figure out how, even after searching how to. I dont know what the hash is either :( . Im trying to learn but dont really have anyone to help me. I did download the 3.1.2.1 last night, deleting older version but i think i can still get in the first wallet. I originally installed it on the 2nd of april, not seeing the newer version, so I may have gotten it  from a bad site. But it says electrum-ltc.org on my history.  On the transaction where i put the money in my account, it has two outputs, is that normal? If im too much of a newbie and you dont feel like going thru this with me i understand completely, but would love and greatly appreciate the help.

**Comment by Harryhobbit** [comment]
Oh and it actually happened on the 4th of april

**Comment by pooler** [comment]
> I originally installed it on the 2nd of april, not seeing the newer version, so I may have gotten it from a bad site.

Version 3.1.2.1 was posted to the official website on March 31, so I'm afraid that appears to be the case. If I were you, I would consider your computer compromised and take appropriate action.

> On the transaction where i put the money in my account, it has two outputs, is that normal?

Yes, one of the outputs is probably change.

**Comment by Harryhobbit** [comment]
By appropriate action,  does that mean wiping the hard drive? And thank u
so much for your help. I sincerely appreciate u spending ur time to. Help
me.

**Comment by pooler** [comment]
> By appropriate action, does that mean wiping the hard drive?

Possibly. I don't know what kind of malware you may have run or what you use your computer for. All I'm saying is that you should consider the risks and act accordingly.

**Comment by Harryhobbit** [comment]
Ok thank u very much I REALLY appreciate you

**Comment by ONYXARC** [comment]
3.1.2.1 FROM litecoin website https://www.litecoin.com/#wallets has VIRUS sprisky.U!  going with a different coin.  honestly i think this is virus implementation from Litecoin itself. I think they are shady thieves

**Comment by pooler** [comment]
@ONYXARC, that's almost surely a false positive, as I've explained [here](https://github.com/pooler/electrum-ltc/issues/175).

**Comment by danbel79** [comment]
Harry, can we get in touch with you, robbed me exactly like what happened to you, retrieved your ltc?
I hope to establish contact!
