### ISSUE TITLE
invalid status 6d00 when offline signing with ledger nano s

### ISSUE THREAD

**Issue by 3ntranced** [pooler/electrum-ltc#178]
Hi, I am getting exception: invalid status 6d00 when I try to sign a transaction file with my ledger nano s. Transaction is from M address to a ltc1 address. I am running todays git clone of electrum-ltc on offline tails os. Thanks

**Comment by pooler** [comment]
Does the same operation work on 3.1.3.1?

**Comment by 3ntranced** [comment]
In 3.1.3.1 it says offline signing with Ledger is not supported. I think you recently merged ledger.py that was changed for electrum so that Ledger can be used to sign offline.

**Comment by pooler** [comment]
Yes, you're right. What firmware and Litecoin app versions are you using?
Does the error only arise when offline signing transactions to ltc1 addresses?

**Comment by 3ntranced** [comment]
firmaware 1.4.2, litecoin 1.2.5, mcu 1.5. Appears so as M to M addresses works, so must be something with ltc1 address.

**Comment by 3ntranced** [comment]
maybe something to do with displaying the ltc1 address on the screen

**Comment by pooler** [comment]
Have you tested the analogous operation (P2SH to bech32) with Electrum (for Bitcoin)?

**Comment by 3ntranced** [comment]
yes. bc1 to bc1 works offline on git electrum with ledger nano s BUT it doesnt ask to confirm output 1 on the ledger screen, it goes straight to confirmation of output 2. Should I open an issue about that on electrum git?

**Comment by 3ntranced** [comment]
3 to bc1 same story

**Comment by pooler** [comment]
OK, so if I understand what you're saying correctly this does work for Bitcoin. What about online signing a P2SH to bech32 transaction with Electrum-LTC?

**Comment by 3ntranced** [comment]
You understood correctly. Online signing gives the same error

**Comment by 3ntranced** [comment]
Traceback (most recent call last):
  File "/home/a/1/electrum-ltc/plugins/ledger/ledger.py", line 440, in sign_transaction
    outputData = self.get_client().finalizeInput(b'', 0, 0, changePath, bfh(rawTx))
  File "/usr/local/lib/python3.5/dist-packages/btchip/btchip.py", line 311, in finalizeInput
    response = self.dongle.exchange(bytearray(apdu))
  File "/usr/local/lib/python3.5/dist-packages/btchip/btchipComm.py", line 127, in exchange
    raise BTChipException("Invalid status %04x" % sw, sw)
btchip.btchipException.BTChipException: Exception : Invalid status 6d00
Traceback (most recent call last):
  File "/home/a/1/electrum-ltc/plugins/ledger/ledger.py", line 440, in sign_transaction
    outputData = self.get_client().finalizeInput(b'', 0, 0, changePath, bfh(rawTx))
  File "/usr/local/lib/python3.5/dist-packages/btchip/btchip.py", line 311, in finalizeInput
    response = self.dongle.exchange(bytearray(apdu))
  File "/usr/local/lib/python3.5/dist-packages/btchip/btchipComm.py", line 127, in exchange
    raise BTChipException("Invalid status %04x" % sw, sw)
btchip.btchipException.BTChipException: Exception : Invalid status 6d00

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/a/1/electrum-ltc/gui/qt/util.py", line 645, in run
    result = task.task()
  File "/home/a/1/electrum-ltc/lib/wallet.py", line 1500, in sign_transaction
    k.sign_transaction(tx, password)
  File "/home/a/1/electrum-ltc/plugins/ledger/ledger.py", line 44, in catch_exception
    return func(self, *args, **kwargs)
  File "/home/a/1/electrum-ltc/plugins/ledger/ledger.py", line 247, in wrapper
    return func(self, *args, **kwargs)
  File "/home/a/1/electrum-ltc/plugins/ledger/ledger.py", line 500, in sign_transaction
    self.give_error(e, True)
  File "/home/a/1/electrum-ltc/plugins/ledger/ledger.py", line 240, in give_error
    raise Exception(message)
Exception: Exception : Invalid status 6d00

**Comment by pooler** [comment]
I talked to @btchip and he said that the current Litecoin build does not support native segwit. This should be fixed in the next version of the Litecoin app.

**Comment by 3ntranced** [comment]
thanks. and litecoin app is on ledger's end so that just depends on how fast or slow they move?

**Comment by pooler** [comment]
@3ntranced Correct.

**Comment by 3ntranced** [comment]
nothing yet huh? any word on the next version of litecoin app?

**Comment by russoj88** [comment]
Confirmed same issue on Ledger App v1.2.8

**Comment by RaghavSood** [comment]
Attaching the APDU logs from such a transaction for reference
[ltc_apdus.txt](https://github.com/pooler/electrum-ltc/files/2271398/ltc_apdus.txt)

**Comment by pooler** [comment]
@btchip confirmed that the issue is still present in 1.2.8. A fix is going to be deployed in the next version of the Litecoin app.

**Comment by pooler** [comment]
I presume this has been resolved. If this is still an issue, please re-open.

**Comment by russoj88** [comment]
@pooler working for me with Litecoin app version 1.3.7!

**Comment by rok1206** [comment]
I have still the same problem with the latest firmware 1.5.5 and litecon hangs on confirmation never display the address to confirm on device....
