### ISSUE TITLE
Multisig Issues

### ISSUE THREAD

**Issue by raymondcarl** [pooler/electrum-ltc#179]
I came across 2 known multi-sig related issues that exist in both the parent Electrum repo and the LTC repo.

**cosigner pool down frequently**  Seems to be solved by restart, but the frequent need for restarting the cosigner pool suggests that maybe there is a better way.

**QR code import doesn't work**  ZBar for python seems to be a ghost package now and the developers left the QR code functionality in Electrum incase the repo is picked back up in the future.

How do you deal with issues like this generally with opensource where something is done well or right in the parent repo?  If you try to improve functionality and do something different, you are creating a lot of work for this fork to check compatibility in the future and maintenance seems to be a pain in the ass.  So, I'm just asking in general how you approach these areas?

On the other hand, it seems like there could be something done to improve the functionality for multi-sig as I think it is a critical feature to help users maintain some semblance of decentralisation rather than everyone maintaining a coinbase account.  Do you see multi-sig functionality as a high priority issue?

(multi-sig functionality works in Electrum today, but I just mean in terms of making it smoother for users to make it more attractive)

**Comment by pooler** [comment]
Electrum-LTC is simply a port of Electrum to Litecoin. Any development work that is not specific to Litecoin should be directed upstream, so that both projects can easily benefit from it.

**Comment by raymondcarl** [comment]
OK.  You can close this issue.
