### ISSUE TITLE
Is this a Exodus/SegWit/Electrum-LTC mess? Electrum-LTC shows "Balance: 0", no transaction in or out, but LTC are still there.

### ISSUE THREAD

**Issue by ZaneCEO** [pooler/electrum-ltc#180]
Up until February I used to keep my LTCs in Exodus. Later on (Feb. 19) I installed Electrum-LTC via sudo `sudo pip3 install https://electrum-ltc.org/download/Electrum-LTC-3.0.6.2.tar.gz.tar.gz` (command taken from my history).

I created a new **SegWit** wallet in Electrum-LTC. I was provided with a `ltc1...` address.

I sent 0.1 LTC from Exodus to said address. After a couple of seconds, the transaction went through: I received my 0.1 LTC in Electrum-LTC, so I sent the remaining LTCs from Exodus to the Electrum-LTC address as well. I saw them in Electrum-LTC too.

I never had a look at it again since today.

When I opened Electrum-LTC today, **I see my LTC balance as zero**. I don't see any history in the main window.

I quickly went back to Exodus, were I see my two transaction to the Electrum-LTC address... but I now realize that the receiving address is different: it isn't the `ltc...` I sent LTCs to, but a `LSy...` I never saw before. I'm absolutely, 100% bet-my-life-on-it sure that I saw my LTCs arriving in Electrum-LTC, so I think that the two addresses are one and the same, just in a different format....

So, my questions are:

1. How can I convert my Electrum-LTC/SegWit address to a non-SegWit address to see if the two match?
1. Most important: **how can I get my LTCs back?**

**Comment by pooler** [comment]
According to their [website](https://www.exodus.io/releases/), Exodus has only supported sending to bech32 addresses since version 1.47.0, which was released on March 15, 2018 (and apparently only BTC was supported). I cannot reconcile this with your description, as you say you sent the coins to a bech32 address in February.

On a minor note, the command from your history has a `.tar.gz` too much and must have given an error; I suppose you then corrected it, though.

No conversion can be made between bech32 addresses (starting with `ltc1`) and regular P2PKH addresses (starting with `L`). They represent two very different things, it's not just a matter of format.

Any chance you could post the transaction IDs?

**Comment by ZaneCEO** [comment]
Hi pooler,
thanks for your reply. I didn't sleep at all in the past day and I've already thrown up multiple times, so your support really means the world to me.

I originally sent LTCs from Exodus to ltc1qnnepcp9l5ldhe89tvyy58gwa53f9dzrrz0y4s6

The address currently holding my LTC is this: http://explorer.litecoin.net/address/LSyjJLxCvBKBPGaHWqVS2pHVWA65WvoYRT

These are the trasaction reported by Exodus:

https://live.blockcypher.com/ltc/tx/a32ee7d3f7deb62511037afbb31cdbb217f95c84658855e9d5ba41132d150ba9/

https://live.blockcypher.com/ltc/tx/6b11aa41808a1acf03924e6b45a0a3c27238504786072446e668cd01acb33d74/

Again: I'm 100% positive that I saw the coin in Electrum-LTC : the first 0.1 LTC was sent exactly for that purpose, and I saw it arriving.

**Comment by pooler** [comment]
It seems that no transactions were ever sent to address [ltc1qnnepcp9l5ldhe89tvyy58gwa53f9dzrrz0y4s6](https://chain.so/address/LTC/ltc1qnnepcp9l5ldhe89tvyy58gwa53f9dzrrz0y4s6). What makes you believe that you entered that address in Exodus? As I pointed out earlier, Exodus should have rejected such an address, as it had no bech32 support.

Could it be that you had a different wallet loaded in Electrum-LTC?

**Comment by ZaneCEO** [comment]
> Could it be that you had a different wallet loaded in Electrum-LTC?

Unlikely, but that's seems to be the only logical explanation. Is there a "pattern" to find all my Electrum-LTC wallets on disk? I mean: a header or something I can put in `grep -r 'electrum-standard-header' /` ?

**Comment by ZaneCEO** [comment]
Hi Pooler
this is to let you know that I've recovered all of my LTC!

I don't know what happened really: I found out I had another LTC wallet on another PC and my coins where there! It's a mystery to me how it is possible that I saw the coin deposited from my first PC, but that's it!

Thanks again for your formidable support during my crisis.
