### ISSUE TITLE
Help, can't send coins on an exchanger

### ISSUE THREAD

**Issue by Mixa37rus** [pooler/electrum-ltc#190]
Hi. I have a problem. Can't send to exchange coins from electrum wallet lc 3.1.3.1. When I click on the " send "button, the"sign transaction" window appears. This window hangs for a long time, and then the error crashes. When sending any number of coins, the Commission is taken to be 0.1 ltc. After translating the text from the error window, I realized that it was because of a very large Commission. I put a Commission on a minimum, but still asks for the transfer of coins 0.1 ltc. Help please.

**Comment by pooler** [comment]
What does the error message say, exactly?
How many transactions are in this wallet?

**Comment by Mixa37rus** [comment]
error: {'code': 1, 'message': 'the transaction was rejected by network rules.\n\n64: tx-size\n[01000000fda602bb673dfcdc86425ef633352cb6762feb85608e253097ed98fbf5b125b8c22e001f0000006b483045022100c7a5b1a338784f8fd61b91ad819c10dc5dbba0a48569ad8dc4c

**Comment by pooler** [comment]
Could you provide more information about the transaction? Maybe a screenshot of the window you get when you click on the "Preview" button?

**Comment by Mixa37rus** [comment]
![1](https://user-images.githubusercontent.com/43851756/46572603-a4601000-c991-11e8-8364-c7085c5e3fdc.jpg)
![2](https://user-images.githubusercontent.com/43851756/46572604-a4f8a680-c991-11e8-96ae-3abd13acb8e4.jpg)
![3](https://user-images.githubusercontent.com/43851756/46572605-a4f8a680-c991-11e8-9dbc-9ff13f862bf4.jpg)
![4](https://user-images.githubusercontent.com/43851756/46572606-a4f8a680-c991-11e8-8f36-c10e3c4496eb.jpg)
![5](https://user-images.githubusercontent.com/43851756/46572661-8941d000-c992-11e8-8298-f07d6c9aca53.jpg)
![6](https://user-images.githubusercontent.com/43851756/46572662-89da6680-c992-11e8-9606-b10729c000cd.jpg)

**Comment by pooler** [comment]
Are you sure that you clicked on the Preview button ("предпросмотр") as I asked?

 How many transactions are in this wallet?

Also, which server are you connected to? Have you tried connecting to a different server manually?

**Comment by Mixa37rus** [comment]
I tried to connect both in the automatic mode, and choosing servers manually. Nothing changes. Sorry that just do not understand about what kind of "preview" you said. Send a screenshot.
![1](https://user-images.githubusercontent.com/43851756/46573156-b04fd000-c999-11e8-87c4-bf9838d5b60c.jpg)

**Comment by Mixa37rus** [comment]
![7](https://user-images.githubusercontent.com/43851756/46574053-6faa8380-c9a6-11e8-9df3-6807011651c2.jpg)

**Comment by pooler** [comment]
OK, I expected the number of inputs to go down but it stayed the same (677). I guess you must have a large number of tiny outputs from previous transactions in this wallet. To see them, click on "View" > "Show Coins" (or the equivalent in your language) in the top menu. Try selecting as many as necessary to make the amount that you want to send, but not more than about a hundred of them; then, right-click and select "Spend". Enter the destination address and the amount you wish to send. See if this way it allows you to send the transaction.

**Comment by Mixa37rus** [comment]
Thank you, Thank you very much dear friend. After your last piece of advice, it worked. The first time with so faced.
