### ISSUE TITLE
CAN'T SEND LTC, STILL SYNCHRONIZING 

### ISSUE THREAD

**Issue by kryst51** [pooler/electrum-ltc#195]
Hi, I use Electrum - LTC 2.9.3.1 and I can't send LTC. It's synchronizing. 
![image](https://user-images.githubusercontent.com/44819765/48094193-c6a7b080-e211-11e8-80bd-beeed5c80624.png)

**Comment by pooler** [comment]
Please upgrade to version 3.1.3.1.
https://electrum-ltc.org/
