### ISSUE TITLE
Invalid address when want to send to segwit address

### ISSUE THREAD

**Issue by aghamir** [pooler/electrum-ltc#200]
Hi @pooler ,
Electrum-ltc raised `Invalid address` when using segwit address which begins with "3" as a target address in `personal.sendTransaction`. Maybe it is from upstream, though.

**Comment by pooler** [comment]
Support for legacy P2SH addresses (starting with `3`) was dropped some time ago. You can convert them to the new format (starting with `M`) using this tool: https://litecoin-project.github.io/p2sh-convert/
