### ISSUE TITLE
Has Electrum-LTC fixed the phishing attack issue?

### ISSUE THREAD

**Issue by andronoob** [pooler/electrum-ltc#205]
https://github.com/spesmilo/electrum/issues/4968
It seems that https://electrum-ltc.org/ is still not updated.

**Comment by pooler** [comment]
The issue is fixed in the git repo, and for instance version 3.3.3.1 has already been tagged. Official binaries should be made available shortly (I've asked a member of the Core team to make code-signed builds).

**Comment by andronoob** [comment]
Thanks. Closing this.
