### ISSUE TITLE
Catastrophic crash when receiving second payment

### ISSUE THREAD

**Issue by hhassey** [pooler/electrum-ltc#207]
today I made a second deposit to the wallet and upon first notice of receipt I got this crash.
now I can't open the wallet. please advice.

Traceback (most recent call last):
  File "/opt/Electrum-LTC-3.3.3.1/electrum_ltc/gui/qt/history_list.py", line 83, in lessThan
    if v1 is None or isinstance(v1, Decimal) and v1.is_nan(): v1 = -float("inf")
TypeError: isinstance() arg 2 must be a type or tuple of types
Aborted

**Comment by pooler** [comment]
Not sure what you mean by "catastrophic", but this crash is due to an incompatibility with PyQt 5.12 which has already been fixed in the git repo. You can either use PyQt 5.11, run Electrum-LTC from git master, or wait for the release of official 3.3.4.1 binaries.

**Comment by hhassey** [comment]
Thanks @pooler for your quick response. Maybe I exagerated but the "Catastrophic" was because I can't open the program and I fear for my coins.  I will try to download from Git and will report back. thanks again.

**Comment by hhassey** [comment]
Thanks @pooler I did download from Git and it is working perfectly. Thanks so much.
