### ISSUE TITLE
First time user Can't Create New Wallet

### ISSUE THREAD

**Issue by benzmuircroft** [pooler/electrum-ltc#21]
Hi,

I am on xUbuntu latest version. I followed the install instructions on your site:

sudo apt-get install python-qt4 python-pip python-dev
sudo apt-get install python-slowaes  # on Ubuntu 13.10 and higher
sudo pip install https://electrum-ltc.org/download/Electrum-LTC-1.9.8.6.tar.gz

So then I open electrum-ltc

and I am asked:

Electrum could not find an existing wallet. What do you want to do? Create New or Restore.. & Standard Wallet.

I choose create new standard wallet and click next...

Then the app flashes and hops up toward the top of the screen a little with the exact same screen saying

Electrum could not find an existing wallet. What do you want to do? Create New or Restore.. & Standard Wallet.

So I click next

Then the app flashes, doesn't hop but, still showing with the exact same screen saying

Electrum could not find an existing wallet. What do you want to do? Create New or Restore.. & Standard Wallet.

So I click next

this time (everytime after three clicks) the app closes its self.

I have the btc version of electrum installed already running fine. do you think that they conflict?

I also tried installing a lower version and the same thing happens on electrum-ltc version 1.9.8.5

**Comment by pooler** [comment]
Please try with the latest release candidate and see if the problem persists.
https://litecointalk.org/index.php?topic=18608.msg265384#msg265384

**Comment by benzmuircroft** [comment]
Worked like a charm!
