### ISSUE TITLE
keepkey webusb support

### ISSUE THREAD

**Issue by keepkeyjon** [pooler/electrum-ltc#212]
Not sure what your schedule is for merging from upstream, but KeepKey's with v6.0.0+ firmware won't be able to talk to electrum-ltc until this gets pulled from upstream: https://github.com/spesmilo/electrum/pull/5205

**Comment by pooler** [comment]
Upstream patches are usually merged within a couple days.

The patch in question has now been merged, so I'm going to close this ticket; feel free to reopen it if there are any issues.

**Comment by keepkeyjon** [comment]
Thank you!

How often is the release cycle, is it roughly the same as upstream?

**Comment by pooler** [comment]
@keepkeyjon I would say releases are not as frequent as upstream ones. As a general rule, it all depends on the perceived stability of the new version and on the importance of the changes it brings.
