### ISSUE TITLE
Consistent "unspent outputs" problem from HitBTC to electrum-LTC?  125 LTC unspent, 4 months waiting

### ISSUE THREAD

**Issue by miltonc90** [pooler/electrum-ltc#219]
My issue is 125 LTC sent from HitBTC to Electrum-LTC, never received the LTC and the blockchain search shows my transaction was "unspent", but the rest of the transactions on the block were "sent".  It has been 4 months and I contacted HitBTC support.  Hoping I can get some info from the electrum-LTC developers on this issue.

Here is a link to another github thread about this problem, the same one I am having
https://github.com/blockcypher/explorer/issues/228

Here is my transaction ID on the LTC blockchain
https://live.blockcypher.com/ltc/address/LPSPRZvLsADKTKmV3EhHxsW16592d4dRgK/

**Comment by pooler** [comment]
The transaction on the page you linked to is confirmed, and there is nothing wrong with it. The output is

**Comment by bitcoingenerator** [comment]
Upgrade to the latest Electrum LTC wallet ([version 3.3.6](url=https://electrumlitecoin.org)) with some security updates.

**Comment by pooler** [comment]
> Upgrade to the latest Electrum LTC wallet version 3.3.6 at [...]

This is an obvious attempt to make you download malware.
The latest version of Electrum-LTC is 3.3.5.1. Never download updates from sources other than electrum-ltc.org.

**Comment by miltonc90** [comment]
I was running an electrum-LTC version 2.9.something, and I updated to 3.3.5.1 (using the OSX executable file from <https://electrum-ltc.org/download/electrum-ltc-3.3.5.1.dmg>) and it seems to have immediately recognized the 125 LTC.  It still says "unspent" on the blockchain, so I guess I didn't understand what that term means.
