### ISSUE TITLE
hi pooler

### ISSUE THREAD

**Issue by doged** [pooler/electrum-ltc#22]
i made a fork of this, and im having trouble getting the wallet to create a proper wallet address, it keeps making litecoin addys.. can you tell me where this setting is, as i cant search this repo..

**Comment by pooler** [comment]
This is an issue tracker, not a help forum.

Anyway, frankly, if you can't handle something as basic as changing address version bytes, you should probably refrain from making a port of Electrum. You risk ending up with *lots* of bugs.
