### ISSUE TITLE
deprecated warning python 3.7

### ISSUE THREAD

**Issue by sirnicolas21** [pooler/electrum-ltc#220]
there is a deprecation warning popping out in every action in electrum-ltc

` Error: /home//.local/lib/python3.7/site-packages/google/protobuf/internal/api_implementation.py:154: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from google.protobuf.pyext import _message
/home//.local/lib/python3.7/site-packages/google/protobuf/internal/containers.py:182: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  MutableMapping = collections.MutableMapping
/home//.local/lib/python3.7/site-packages/scrypt/scrypt.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/home//.local/bin/electrum-ltc", line 414, in <module>
    result = server.run_cmdline(config_options)
  File "/home//.local/lib/python3.7/site-packages/jsonrpclib/jsonrpc.py", line 748, in __call__
    return self.__send(self.__name, args)
  File "/home//.local/lib/python3.7/site-packages/jsonrpclib/jsonrpc.py", line 630, in _request
    check_for_errors(response)
  File "/home//.local/lib/python3.7/site-packages/jsonrpclib/jsonrpc.py", line 1321, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32603, 'Server error: File "/home//.local/lib/python3.7/site-packages/electrum_ltc/network.py", line 834, in make_reliable_wrapper | electrum_ltc.network.BestEffortRequestFailed: no interface to do request on... gave up.\n')
`

**Comment by pooler** [comment]
As far as I can tell this is not specific to Electrum-LTC, as the same deprecation warning is emitted when running the latest Electrum. Feel free to report upstream.

**Comment by sirnicolas21** [comment]
well that might be the case, but i don't have the same warning in btc electrum
