### ISSUE TITLE
Unable to build AppImage correctly

### ISSUE THREAD

**Issue by margre8** [pooler/electrum-ltc#230]
After build Electrum-ltc 3.3.8.1 AppImage and compare files via sha256sum I see AppImages aren't same.

### Release
`deaa3d17bef124efbf5da4d49eab9272eacb5633e7bd02bd394d47e2991d92a4`

### My build
`cc4c6644cfebcbf4ce5166b921e51ddf246d51db37f9d518405f9cb7770080dc`

And after extract both AppImages via `./AppImage --appimage-extract` and compare with `diff -q -r` I see there is a some extra files and folder only in Release AppImage:

> /usr/lib/python3.6/site-packages/electrum_ltc/gui/qt: icons_rc.py
> /usr/lib/python3.6/site-packages/electrum_ltc/plugins/trezor: client.py
> /usr/lib/python3.6/site-packages/electrum_ltc/plugins/trezor: transport.py
> /usr/lib/python3.6/site-packages/electrum_ltc: plugins.py
> /usr/lib/python3.6/site-packages/: electrum_ltc_gui
> /usr/lib/python3.6/site-packages/: electrum_ltc_plugins

Thank you for help

**Comment by margre8** [comment]
In original Electrum is problems with `usr/lib/python3.6/site-packages` too, see: https://github.com/spesmilo/electrum/issues/5859

**Comment by margre8** [comment]
@pooler Please have you some tip why is these files (.py files, no .so files) are included in release?
Because I can't see these files in source code.

Thank you for help

**Comment by pooler** [comment]
@margre8 I'm not sure. I hope I will find some time to look into it soon.

**Comment by pooler** [comment]
This appears to have been fixed by spesmilo#6843
