### ISSUE TITLE
daemon  mode

### ISSUE THREAD

**Issue by FIVIL** [pooler/electrum-ltc#234]
Hi, is it possible to use electrum-LTC in daemon mode just like the original electrum wallet for BTC??

I have a working application that works with electrum wallet JSON-RPC perfectly, and now I want to add LTC support to my application, and I was wondering if electrum-LTC has daemon mode and JSON-RPC support as well? and if it does, how different it maybe with the original electrum wallet?

My main concern here is how much change I must do to my code in order to get it to work with electrum-LTC!!!!

**Comment by pooler** [comment]
The daemon should work in exactly the same way. Electrum-LTC aims to be as close to Electrum as possible.

**Comment by FIVIL** [comment]
Thank you.
