### ISSUE TITLE
Please enter a valid address.

### ISSUE THREAD

**Issue by 1803jose** [pooler/electrum-ltc#236]
Good evening, I am hereby addressing you to notify you that I am having trouble with my litecoin address to receive my cryptocurrencies from one address to another when I place it to the recipient or who to send to me says Please enter a valid address. Because of this I have not been able to receive my coins in my Electrum wallet, then I add more details of my address and wallet:

Wallet Address: ltc1qg0pmq8ajyvgz5f7306hlmcmms9uchvuhncn6h6

Wallet where to receive my Eletrum-LTC 3.3.8.1 coins - default_wallet (standard).

Please, if you can solve my problem, I have tried everything until I downloaded the electrum ltc 3.3.8.1 wallet several times to see if I downloaded it well but continue to throw the same address to receive .. I need your valuable help to solve my problem thanks .....
My email: joseluisgraterol1@outlook.es

**Comment by pooler** [comment]
> ltc1qg0pmq8ajyvgz5f7306hlmcmms9uchvuhncn6h6

That's a valid Segwit bech32 address.

When creating a wallet you have to choose between Segwit and Legacy, and Electrum-LTC shows this warning:

> Segwit wallets use bech32 addresses, defined in BIP173. Please note that websites and other wallets may not support these addresses yet. Thus, you might want to keep using a non-segwit wallet in order to be able to receive litecoins during the transition period.

**Comment by 1803jose** [comment]
Ah ok no lo sabia gracias... no mire que me pidiera esa opción, volveré a crear otra cartera con esa características... GRACIAS por su buena asistencia muchas gracias

**Comment by 1803jose** [comment]
Buenas tardes Sr, Pooler, por medio de este me dirijo a usted para pedirle o hacerle la pregunta si hay la posibilidad de tener una billetera de electrum-doge, quisiera saber si hay alguna aplicación de escritorio para bajarla e instalarla en mi ordenador pc quiero tener una billetera electrum doge por que me ha funcionado bien y me gusta como se comporta son una buena billetera ligera y muy eficiente quiero saber si aparte de electrum bitcoin, electrum dash, electrum bitcoin cash, electrum litecoin, habrá una billetera electrum que sea para guardar  mis doge.... O de otras monedas que no sea las antes mencionadas  Por favor si hay alguna aplicación electrum wallet favor hacerme llegar el links para descargarla.

Sin mas que hacer referencia y en espera de su valiosa ayuda se despide:   Jose

Mi correo joseluisgraterol1@outlook.es
