### ISSUE TITLE
Trezor Wallet not recognized 

### ISSUE THREAD

**Issue by yohaaan** [pooler/electrum-ltc#238]
**Expected behavior**

- when creating a new wallet and  at Keystore step - Use a hardware device option is selected user should be able to access his wallet 

**Actual behavior**

- when creating a new wallet and hardware device option is selected and Trezor wallet is used as a keystore option the device is not detected and the following error message is displayed:

![image](https://user-images.githubusercontent.com/37402530/75978582-23d37500-5edf-11ea-8948-13ac4a864186.png)

The same exact device is, however,  recognized by the computer and by Electrum and Trezor Wallet (https://wallet.trezor.io/), Exodus Wallet etc.

**Environment**

- Model: Trezor One & Trezor T - both on the latest firmware version

- OS: NixOS 19.09.2199.d1918bb0d90 (Loris), 64-bit

**Comment by pooler** [comment]
Please specify Electrum-LTC version and how it was installed on this particular machine.

**Comment by yohaaan** [comment]
Electrum LTC - electrum-ltc-3.1.3.1
https://github.com/NixOS/nixpkgs/blob/release-19.09/pkgs/applications/misc/electrum/ltc.nix
installed on NixOS

**Comment by pooler** [comment]
Please use the latest version from the official website of Electrum-LTC.

**Comment by pooler** [comment]
No response, closing.
