### ISSUE TITLE
Error exporting transaction for signing

### ISSUE THREAD

**Issue by Scollop355** [pooler/electrum-ltc#241]
Unable to increase fee for a Litecoin unconfirmed transaction which I sent at  0.9 sats. 

I "increase fee" to 3 sats then "export" and when I click "save" I get;

"Sorry!  Something went wrong while executing Electrum."  ￼

Will LTC Electrum allow bumping the fee via exporting to sign air gapped?  This also happens on the BTC Version of Electrum.

**Comment by pooler** [comment]
> This also happens on the BTC Version of Electrum.

Issues that are not specific to Electrum-LTC should be reported upstream only.
