### ISSUE TITLE
Cant send LTC to another LTC (of mine)

### ISSUE THREAD

**Issue by carlospit007** [pooler/electrum-ltc#242]
hi 

I mistakenly sent 1 LTC to my BTC address, now I downloaded ltc electron and see my 1 ltc on the wallet, trying to transfer it to my LTC wallet, when I click sign in to send the transaction I get an annoying error. Please help . thank you :)

![image](https://user-images.githubusercontent.com/68308636/87491463-cfb76a80-c60d-11ea-950c-2abe9616f56f.png)

**Comment by pooler** [comment]
A few points seem unclear.

> I mistakenly sent 1 LTC to my BTC address,

Did you send to an address starting with `3`? Any other type of Bitcoin address should have been rejected. How was this Bitcoin address generated?

> now I downloaded ltc electron

I presume you mean Electrum-LTC. So the coins were sent using some other wallet software for Litecoin?

> and see my 1 ltc on the wallet,

I don't understand this. You sent 1 LTC to a BTC address, so there must be something you omitted if you're still seeing that 1 LTC being reported as balance somewhere.

**Comment by ndaxio** [comment]
@pooler i am actually in the same situation as above user. i have a friend who sent LTC to BTC address ( start with 3)  and i am trying to help him out.  Once you download an install 3.3.8.1 and detect the LTC ( fully confirmed) and you try to withdrawal to an LTC wallet you get the same exact error as above. is there a newer version than 3.3.8.1 that could potentially fix this? i read on another thread that user updated to 4.0.0b1 and he was able to make it work. I am on windows and dont use python and can not seem to find any newer updates

**Comment by pooler** [comment]
> Once you download an install 3.3.8.1 and detect the LTC ( fully confirmed)

That's the part that I'm failing to understand. What did you do, exactly, to make Electrum-LTC detect the coins?
Also, how the receiving Bitcoin address was generated is of the utmost relevance. Only in specific cases retrieval of the coins using Electrum-LTC will be possible.

**Comment by Emily844** [comment]
Hello guys, 

I am facing the same issue. I wrongly sent LTC from Coinmate to my Trezor wallet generated BTC address (Yes, really stupid mistake). So the address starts with 3. I can see this transaction in Electrum-LTC when connected to my hardware wallet. I wanted to send these LTC to my trezor wallet LTC address, but I am receiving the same error as on the print screen above and signing transaction get stuck on my Trezor Wallet. Any idea how to fix this issue? Or how to get my lost LTC? 

Many thanks.

**Comment by tdeegan51** [comment]
I have the exact same issue and have yet to find the answer. Can someone please answer this question?

**Comment by Emily844** [comment]
@tdeegan51 You can find the solution under this thread - Error during signing transaction with Trezor #247.

**Comment by dustindog101** [comment]
pls help

**Comment by pooler** [comment]
I still do not understand what the OP did, but the specific error should be fixed in 4.0.9.1.
