### ISSUE TITLE
Electrum LTC tries to access weird paths on Ledger

### ISSUE THREAD

**Issue by My1** [pooler/electrum-ltc#244]
Ledger Recently introduced derivation path checks for the applets related to bitcoin and electrum LTC tries to access 3 paths that are seen as unusual and therefore bring warnings.

1) 44'
2) 4541509'
3) 4541509'/1112098098'

it might be useful to either remove the access to these paths or talk to the Ledger people to get the warnings out if there are valid reasons for the paths and they are not unusual.

**Comment by pooler** [comment]
See also: https://github.com/spesmilo/electrum/issues/6511

**Comment by My1** [comment]
while that explains `4541509'/1112098098'`, why does it ask for the 44 root and the 4541509 "root" public keys?

**Comment by pooler** [comment]
The behavior is the same as with upstream Electrum. There is more information at spesmilo#6512.
Ledger should be deploying a new version of their Litecoin application soon to fix the issue.
An additional workaround has been applied upstream and has been merged into Electrum-LTC today.
Closing this ticket for now, please reopen if needed.
