### ISSUE TITLE
docker build step 5 android / kivy failed due to missing theme files light-0.png

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [pooler/electrum-ltc#245]
i followed all steps to the last 5. Of 

https://github.com/spesmilo/electrum/tree/master/contrib/android

but it fails with:

```
```

  electrum-ltc git:(master) ✗ sudo docker run -it --rm \

    --name electrum-android-builder-cont \

    -v $PWD:/home/user/wspace/electrum \

    -v $PWD/.buildozer/.gradle:/home/user/.gradle \

    -v ~/.keystore:/home/user/.keystore \

    --workdir /home/user/wspace/electrum \

    electrum-android-builder-img \

    ./contrib/android/make_apk

~/wspace/electrum/contrib/android ~/wspace/electrum

#bash -c 'for i in network lightning; do convert -background none theming/light/.{svg,png}; done'

python3 -m kivy.atlas ../../electrum-ltc/gui/kivy/theming/light 1024 ../../electrum-ltc/gui/kivy/theming/light/*.png

[WARNING] [Config      ] Older configuration version detected (0 instead of 21)

[WARNING] [Config      ] Upgrading configuration in progress.

[INFO   ] [Logger      ] Record log in /home/user/.kivy/logs/kivy_20-08-31_0.txt

[INFO   ] [Kivy        ] v2.0.0rc3, git-20c14b2, 20200615

[INFO   ] [Kivy        ] Installed at "/home/user/.local/lib/python3.8/site-packages/kivy/__init__.py"

[INFO   ] [Python      ] v3.8.2 (default, Jul 16 2020, 14:00:26) 

[GCC 9.3.0]

[INFO   ] [Python      ] Interpreter at "/usr/bin/python3"

[INFO   ] [Atlas       ] create an 1024x1024 rgba image

 Traceback (most recent call last):

   File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main

     return _run_code(code, main_globals, None,

   File "/usr/lib/python3.8/runpy.py", line 86, in _run_code

     exec(code, run_globals)

   File "/home/user/.local/lib/python3.8/site-packages/kivy/atlas.py", line 448, in <module>

     ret = Atlas.create(outname, filenames, size, **options)

   File "/home/user/.local/lib/python3.8/site-packages/kivy/atlas.py", line 372, in create

     outimage.save('%s-%d.png' % (outname, idx))

   File "/home/user/.local/lib/python3.8/site-packages/PIL/Image.py", line 2155, in save

     fp = builtins.open(filename, "w+b")

 FileNotFoundError: [Errno 2] No such file or directory: '../../electrum-ltc/gui/kivy/theming/light-0.png'

make: *** [Makefile:9: theming] Error 1
```


```

i also tried the steps https://github.com/spesmilo/electrum/tree/master/contrib/android#kivy-can-be-run-directly-on-linux-desktop-how

```
`  android git:(master) ✗ sudo docker run -it --rm \                       

    -v $PWD:/home/user/wspace/electrum \

    -v $PWD/.buildozer/.gradle:/home/user/.gradle \

    --workdir /home/user/wspace/electrum \

    electrum-android-builder-img

To run a command as administrator (user "root"), use "sudo <command>".

See "man sudo_root" for details.



user@c79d4680a124:~/wspace/electrum$ cd contrib/android/; make theming  

bash: cd: contrib/android/: No such file or directory

#bash -c 'for i in network lightning; do convert -background none theming/light/.{svg,png}; done'

python3 -m kivy.atlas ../../electrum-ltc/gui/kivy/theming/light 1024 ../../electrum-ltc/gui/kivy/theming/light/*.png

[WARNING] [Config      ] Older configuration version detected (0 instead of 21)

[WARNING] [Config      ] Upgrading configuration in progress.

[INFO   ] [Logger      ] Record log in /home/user/.kivy/logs/kivy_20-08-31_0.txt

[INFO   ] [Kivy        ] v2.0.0rc3, git-20c14b2, 20200615

[INFO   ] [Kivy        ] Installed at "/home/user/.local/lib/python3.8/site-packages/kivy/__init__.py"

[INFO   ] [Python      ] v3.8.2 (default, Jul 16 2020, 14:00:26) 

[GCC 9.3.0]

[INFO   ] [Python      ] Interpreter at "/usr/bin/python3"

[INFO   ] [Atlas       ] create an 1024x1024 rgba image

 Traceback (most recent call last):

   File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main

     return _run_code(code, main_globals, None,

   File "/usr/lib/python3.8/runpy.py", line 86, in _run_code

     exec(code, run_globals)

   File "/home/user/.local/lib/python3.8/site-packages/kivy/atlas.py", line 448, in <module>

     ret = Atlas.create(outname, filenames, size, **options)

   File "/home/user/.local/lib/python3.8/site-packages/kivy/atlas.py", line 372, in create

     outimage.save('%s-%d.png' % (outname, idx))

   File "/home/user/.local/lib/python3.8/site-packages/PIL/Image.py", line 2155, in save

     fp = builtins.open(filename, "w+b")

 FileNotFoundError: [Errno 2] No such file or directory: '../../electrum-ltc/gui/kivy/theming/light-0.png'

make: *** [Makefile:9: theming] Error 1

user@c79d4680a124:~/wspace/electrum$ cat /home/user/.kivy/logs/kivy_20-08-31_0.txt

[INFO   ] Logger: Record log in /home/user/.kivy/logs/kivy_20-08-31_0.txt

[WARNING] [Config      ] Upgrading configuration in progress.

[WARNING] [Config      ] Older configuration version detected (0 instead of 21)

[INFO   ] Kivy: v2.0.0rc3, git-20c14b2, 20200615

[INFO   ] Kivy: Installed at "/home/user/.local/lib/python3.8/site-packages/kivy/__init__.py"

[INFO   ] Python: v3.8.2 (default, Jul 16 2020, 14:00:26) 

[GCC 9.3.0]

[INFO   ] Python: Interpreter at "/usr/bin/python3"

[INFO   ] Atlas: create an 1024x1024 rgba image

[WARNING] stderr: Traceback (most recent call last):

[WARNING] stderr:   File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main

[WARNING] stderr:     return _run_code(code, main_globals, None,

[WARNING] stderr:   File "/usr/lib/python3.8/runpy.py", line 86, in _run_code

[WARNING] stderr:     exec(code, run_globals)

[WARNING] stderr:   File "/home/user/.local/lib/python3.8/site-packages/kivy/atlas.py", line 448, in <module>

[WARNING] stderr:     ret = Atlas.create(outname, filenames, size, **options)

[WARNING] stderr:   File "/home/user/.local/lib/python3.8/site-packages/kivy/atlas.py", line 372, in create

[WARNING] stderr:     outimage.save('%s-%d.png' % (outname, idx))

[WARNING] stderr:   File "/home/user/.local/lib/python3.8/site-packages/PIL/Image.py", line 2155, in save

[WARNING] stderr:     fp = builtins.open(filename, "w+b")

[WARNING] stderr: FileNotFoundError: [Errno 2] No such file or directory: '../../electrum-ltc/gui/kivy/theming/light-0.png'

`
```

i can create the files, can be created by 
`cd contrib/android/; make theming`
in original electrum repo but this failes In ltc repo.

**Comment by pooler** [comment]
First of all, please note that Electrum-LTC on Android is currently untested, unsupported, and most likely bug-ridden.

That said, I just pushed a commit (also untested) that should fix the particular issue you ran into.
