### ISSUE TITLE
Electrum LTC apps not updated

### ISSUE THREAD

**Issue by bosomt** [pooler/electrum-ltc#246]
Can you please build new version of app
to https://electrum-ltc.org/ ?

Latest builds are more than year old and it's not possible to send transactions via Trezor with current firmware versions.

Thank you

**Comment by TrackRunny** [comment]
Yes please, new binary's would be nice if not I can build them myself I guess.

**Comment by pooler** [comment]
Binaries for version 4.0.9.1 are now available.
