### ISSUE TITLE
impersonator (not this) repo contains fake electrum-ltc malware

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [pooler/electrum-ltc#248]
Can you take down this malware electrumltc fake please? Don't follow link **Attention Malware** repo: https://github.com/ ElectrumTeam/electrum-ltc/

i searched for electrum-ltc on github https://github.com/search?q=electrum-ltc and got malware as result.

```
CRC32: 72CE3D9D
MD5: 99B85639B88968A368B55A394176EF7E
SHA-256: 673D2A0787BE7192E3BF0E14CB332C85FB8493469EB525489C1F26D2AC832642
SHA3-256: 13CAC4C089CE68D1F8283F6A1FEF33B115D38ED9DEF1508E9F056F04D0761080

```

https://www.virustotal.com/gui/file/673d2a0787be7192e3bf0e14cb332c85fb8493469eb525489c1f26d2ac832642/detection

Antiy-AVL

Trojan[Backdoor]/MSIL.SpyGate
Arcabit

Trojan.Generic.D2743E17
BitDefender

Trojan.GenericKD.41172503
Bkav

HW32.Packed.
CAT-QuickHeal

Trojan.Agent
Cybereason

Malicious.43bc25
Emsisoft

Trojan.GenericKD.41172503 (B)
FireEye

Trojan.GenericKD.41172503
GData

Trojan.GenericKD.41172503
K7AntiVirus

Adware ( 0054adec1 )
K7GW

Adware ( 0054adec1 )
McAfee

Artemis!9905CB80B361
Rising

Trojan.Crypren!1.B752 (CLASSIC)
Yandex

Trojan.Agent!jKOS93FSwZw

https://www.virustotal.com/gui/file/a4fab4969020a8d919f2d3bb384ad6dd62bebe556592da4c6ee306df152d2194/detection

https://www.virustotal.com/gui/file/40e6235371e777c414cf2744991bff651c98db71273174d7b70ac54a205c85a4/detection

https://www.virustotal.com/gui/file/0064b553ffe90b841ab0d90df214eafe4429e249f5b9cf68e5c6dce1407ffaae/detection

**Comment by pooler** [comment]
This should be reported directly to GitHub. I have forwarded your message.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
The particular noted disappeared thanks. But still some online:
https://github.com/ marc-hayden/electrum-multi-wallet

> `Ad-Aware
> 
> Gen:Variant.Razy.605355
> Alibaba
> 
> TrojanPSW:MSIL/Azorult.6acc8d50
> ALYac
> 
> Gen:Variant.Razy.605355
> Antiy-AVL
> 
> Trojan[PSW]/MSIL.AZORult
> SecureAge APEX
> 
> Malicious
> Arcabit
> 
> Trojan.Razy.D93CAB
> Avast
> 
> Win32:Malware-gen
> AVG
> 
> Win32:Malware-gen
> Avira (no cloud)
> 
> TR/Dropper.Gen
> BitDefender
> 
> Gen:Variant.Razy.605355
> BitDefenderTheta
> 
> Gen:NN.ZemsilF.34196.wq0@aa6A@Yd
> CAT-QuickHeal
> 
> Trojanpws.Msil
> Comodo
> 
> Malware@#e41u3qkk26la
> CrowdStrike Falcon
> 
> Win/malicious_confidence_100% (W)
> Cybereason
> 
> Malicious.f7604d
> Cylance
> 
> Unsafe
> Cynet
> 
> Malicious (score: 100)
> Cyren
> 
> W32/Trojan.HCIJ-3817
> DrWeb
> 
> Trojan.Inject3.22777
> eGambit
> 
> Unsafe.AI_Score_99%
> Elastic
> 
> Malicious (high Confidence)
> eScan
> 
> Gen:Variant.Razy.605355
> ESET-NOD32
> 
> A Variant Of Generik.CTXZRJN
> F-Secure
> 
> Trojan.TR/Dropper.Gen
> FireEye
> 
> Generic.mg.e19508a7e53c5bce
> Fortinet
> 
> MSIL/Azorult.GT!tr.pws
> GData
> 
> Gen:Variant.Razy.605355
> Ikarus
> 
> Trojan.Dropper
> K7AntiVirus
> 
> Riskware ( 0040eff71 )
> K7GW
> 
> Riskware ( 0040eff71 )
> Kaspersky
> 
> HEUR:Trojan-PSW.MSIL.Azorult.gen
> MAX
> 
> Malware (ai Score=82)
> MaxSecure
> 
> Trojan.Malware.73815250.susgen
> McAfee
> 
> PWS-Zbot.gen.gt
> Microsoft
> 
> PWS:Win32/Stimilina.E!rfn
> NANO-Antivirus
> 
> Trojan.Win32.Azorult.fvhqjx
> Palo Alto Networks
> 
> Generic.ml
> Panda
> 
> Trj/GdSda.A
> Qihoo-360
> 
> Win32/Trojan.PSW.a72
> Rising
> 
> Dropper.Generic!8.35E (CLOUD)
> Sangfor Engine Zero
> 
> Malware
> SentinelOne (Static ML)
> 
> DFI - Malicious PE
> Sophos
> 
> Mal/Generic-S
> Sophos ML
> 
> Heuristic
> Symantec
> 
> ML.Attribute.HighConfidence
> Tencent
> 
> Msil.Trojan-qqpass.Qqrob.Ajbh
> TrendMicro
> 
> TROJ_GEN.R002C0PGH20
> TrendMicro-HouseCall
> 
> TROJ_GEN.R002C0PGH20
> VBA32
> 
> TScope.Trojan.MSIL
> VIPRE
> 
> Trojan.Win32.Generic!BT
> Yandex
> 
> Trojan.Agent!A4ZgFUsLqrk
> Zillya
> 
> Backdoor.PePatch.Win32.112596
> ZoneAlarm by Check Point
> 
> HEUR:Trojan-PSW.MSIL.Azorult.gen
> Dr.Web vxCube
> 
> MALWARE

`
