### ISSUE TITLE
Unable to send from Trezor recovered wallet

### ISSUE THREAD

**Issue by RustyNomad** [pooler/electrum-ltc#25]
Tested the recovery of a Trezor based wallet by setting up a wallet on Electrum-LTC using the seed words from Trezor. Wallet loads and updates without problems but unable to send any funds from it. When I click on 'Sign' I get the error 'TrezorWallet' object has no attribute 'plugin'

Had the same on Electrum BTC which I reported and Thomas was able to recreate and fix said problem. So just a heads up to the dev's of the LTC version.

**Comment by pooler** [comment]
This should be fixed now, I'm closing the ticket.
