### ISSUE TITLE
Version tagging and binaries

### ISSUE THREAD

**Issue by RaghavSood** [pooler/electrum-ltc#252]
Mostly a follow up on #226 

There haven't been any new versions tagged, or binaries signed and provided in quite some time now.

Master mostly seems to work with newer features from upstreams, but it would be nice to have version tags at a minimum even if binaries aren't doable at the moment.

I'm looking to update the electurm-ltc package in [nixpkgs](https://github.com/NixOS/nixpkgs/), and we tend to use tagged versions from the upstream repos where possible - switching it over to master commits would result in the packages being tagged "unstable" as they don't have a specific upstream version.

**Comment by TamtamHero** [comment]
:pray: 
The website download link is totally outdated, this version doesn't even work with Ledger devices anymore.

**Comment by pooler** [comment]
Duly noted, thanks. Version 4.0.9.1 was tagged a while ago, so I'm closing this.
