### ISSUE TITLE
Can not create a new wallet without unlocking a previous wallet

### ISSUE THREAD

**Issue by ali-raheem** [pooler/electrum-ltc#255]
### Description

If a wallet exists, you are unable to create a new wallet without unlocking it first. This is undesirable as it unnecessarily means entering your password or connecting a hardware wallet device. Other versions of electrum do not suffer from this problem and offer an create new wallet option.

#### Electrum-ltc
![If a wallet exists, there is no option to create a new wallet](https://user-images.githubusercontent.com/355742/104135893-937d8080-538a-11eb-97ed-3bdd3eb5a2a9.png)

#### Electrum (bitcoin)
![electrum-btc-working](https://user-images.githubusercontent.com/355742/104136106-0e936680-538c-11eb-8441-a4b5a6439d5c.png)

### Reproduction
1. Open electrum-ltc
2. Create a wallet
3. Close electrum-ltc
4. Unplug the hardware wallet - if used.
4. Open electrum-ltc
5. Now you are stuck at a unlock wallet or select file screen (screenshot) either you must enter the password, plug in the wallet, or click cancel and electrum-ltc will quit.

### Work around
Hide wallet from from electrum-ltc, e.g. `mv ~/.electrum-ltc/wallets/default_wallet ~/default_wallet.bak` switch wallets back and forth.

### Tested on

Electrum-ltc 3.3.8.1 AppImage (electrum-ltc-3.3.8.1-x86_64) on Manjaro Linux (Linux Ali-Laptop 5.10.2-2-MANJARO #1 SMP PREEMPT Tue Dec 22 08:14:42 UTC 2020 x86_64 GNU/Linux)

**Comment by pooler** [comment]
This is already implemented in the master branch.

New binary builds should become available soon. But you can also run the code from the git repo.
