### ISSUE TITLE
Ledger devices not recognized 

### ISSUE THREAD

**Issue by TamtamHero** [pooler/electrum-ltc#256]
The release provided on the website doesn't recognize ledger devices anymore, as the Litecoin app has been updated and declares a new USB PID.
Could you please update this very old release and put a recent one like 4.0.9.1 instead ?
Thanks :pray:

**Comment by pooler** [comment]
Duplicate of #246. The Litecoin Foundation has been working on new official binaries.

**Comment by TamtamHero** [comment]
Any link to follow the progress on this ?

**Comment by pooler** [comment]
> Any link to follow the progress on this ? Any ETA ?

No, but it shouldn't take long.

> Are the binaries going to be available on https://electrum-ltc.org/ ?

Yes.

**Comment by ozanyurt** [comment]
Any progress on this?

Thanks
