### ISSUE TITLE
Unable to send from Ledger HW1 Wallet

### ISSUE THREAD

**Issue by JPUnix** [pooler/electrum-ltc#26]
Although the latest version of the code "sees" the HW1 and allows me to create a wallet that uses the HW1 I'm unable to send funds from the wallet. I am first asked to authenticate my HW1 whichworks. But in the process of verifying the transaction using the Ledger security card I'm prompted 3 times to do the "character translation" using the security card. Instead of asking me for the 4th character round the transaction is aborted and I get a message that Electrum-LTC can no longer communicate with the HW1. So in essence I'm completely unable to send LTC.

Is there a fix in the works I hope?

**Comment by pooler** [comment]
When you say "the latest version of the code", are you referring to the latest code from this git repo, or to a released package?

**Comment by JPUnix** [comment]
Sorry about that! It's the latest released package. I'm using Electrum-LTC 2.3.2.2.

**Comment by pooler** [comment]
No problem at all, thank you for reporting this. Could you please check if the same issue affects [RC 2.5.1.1](https://litecointalk.org/index.php?topic=18608.msg288295#msg288295) (remember to backup before testing)?

**Comment by JPUnix** [comment]
That did it! RC 2.5.1.1 fixed the problem.

Thanks!
