### ISSUE TITLE
Electrum-LTC does not recognize my Ledger Nano S

### ISSUE THREAD

**Issue by armcoder89** [pooler/electrum-ltc#261]
Ledger Nano S is not recognized at all by Electrum-LTC.
I bought some LTC several years ago and stored them on my Ledger Nano S and now I am unable to access them because they are supposedly on a legacy account. Electrum-LTC is my only hope of recovering those LTC. 

When I attempt to manually enter the seed,, the Next button stays greyed out. When I try to enter a master key, the Next button remains greyed out. I am basically unable to use Electrum-LTC right now. Am i doing something wrong?

Edit:

I am using an up-to-date Windows 10 PC, Electrum-LTC and a Ledger Nano S.

**Comment by julesGoullee** [comment]
Same here osx 11.2.1 (20D74)

**Comment by julesGoullee** [comment]
@armcoder89 issue solved on my side with the new electrum-ltc version `4.0.9.1`

**Comment by pooler** [comment]
This should be solved in the latest version. If not, please reopen the ticket.
