### ISSUE TITLE
Importing wallet with private key is not enough noob friendly

### ISSUE THREAD

**Issue by slrslr** [pooler/electrum-ltc#269]
Hello, i have installed electrum-ltc 4.0.9.3-1
on Linux and after launching it, i selected to import keys, but the interface for the keys input is not noob friendly:

![](https://i.imgur.com/0KP32st.png)

examples are hard to understand, i would expect examples like:
walletaddress;privatekey

that is what i have, i do not know any more details about it

i ended up pasting just wallet address. Now when trying to send money, it says the transaction is unsigned and the Sign button is grayed out so i am stuck not knowing how to add private key so i can send.

There is menu Wallet/Private keys/Sweep, but i do not understand why to use this, it looks like creating new transaction and paying a fee.

> This wallet is watching-only. This means you will not be able to spend litecoins with it. Make sure you own the seed phrase or the private keys, before you request litecoins to be sent to this wallet.

But i do not want to generate new wallet and empty (sweep?) my existing paper wallet generated using walletgenerator.net 5 years ago. I just want to make occasional payments from existing one and i do not see how.

Thank you in advance for the feedback.

Update: when i imported the wallet by entering private key instead of wallet address (the form shown on the image), then it works to send coins. I think that the wallet/key input field examples should be more intuitive and if user add just wallet address like me, he should be prompted for priv. key possibly.

**Comment by pooler** [comment]
> i ended up pasting just wallet address. Now when trying to send money, it says the transaction is unsigned and the Sign button is grayed out so i am stuck not knowing how to add private key so i can send.

This is consistent with what the interface says (see the screenshot you posted): entering a Litecoin address creates a watch-only wallet.

> I think that the wallet/key input field examples should be more intuitive and if user add just wallet address like me, he should be prompted for priv. key possibly.

This part of the interface is not specific to Litecoin, so you should submit any suggestions about it upstream.
