### ISSUE TITLE
load_wallet fails with timeout

### ISSUE THREAD

**Issue by lbphp** [pooler/electrum-ltc#270]
```
$HOME/.local/bin/electrum-ltc getinfo
Warning: package scrypt not available; synchronization could be very slow
TimeoutError()

$HOME/.local/bin/electrum-ltc load_wallet -w <wallet file>
Warning: package scrypt not available; synchronization could be very slow
Password
TimeoutError()
```

It works with electrum BTC and electrum-dash.
So why not with LTC ?

**Comment by pooler** [comment]
As per the warning, you should have the `scrypt` package installed. How did you install Electrum-LTC?

**Comment by lbphp** [comment]
> As per the warning, you should have the `scrypt` package installed. How did you install Electrum-LTC?

python3 -m pip install --user Electrum-LTC-4.0.9.3.tar.gz

**Comment by lbphp** [comment]
And i have scrypt:
```

sudo apt-get install -y scrypt
Reading package lists... Done
Building dependency tree
Reading state information... Done
scrypt is already the newest version (1.2.1-2).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.

```

**Comment by pooler** [comment]
That's not the Python `scrypt` package. For APT, try `python3-scrypt` instead.

**Comment by lbphp** [comment]
Worked.
Thank you!
