### ISSUE TITLE
`litecoin` URIs not parsed correctly from clipboard

### ISSUE THREAD

**Issue by CharlesJQuarra** [pooler/electrum-ltc#272]
I tried to open a URI `litecoin:LQ6ZBWzHDRdTFqPtu9gHppvWE7Kd3WfbiC?amount=0.02387964&message=Invoice: test-01&label=Foo` from Chrome, but when I open this in Electrum-LTC, I get this error:

```
Error parsing URI:
expected string, not PyQt5.QtCore.QByteArray(b'litecoin:LQ6ZBWzHDRdTFqPtu9gHppvWE7Kd3WfbiC?amount=0.02387964&message=Invoice:%20test-01&label=Foo')`
```

Running Electrum-LTC 4.0.9.3
Mac OS X 10.13.6

**Comment by pooler** [comment]
This appears to be an instance of spesmilo#6933, which has already been fixed in the master branch. The fix will be included in the next release.
