### ISSUE TITLE
aiorpcX 0.22 support

### ISSUE THREAD

**Issue by sbraz** [pooler/electrum-ltc#275]
Hi,
Would it be possible to support newer aiorpcX versions please? At the moment, the Gentoo package works with aiorpcX 0.19.1 but not 0.22.1.

In d86c45edac16e458829b84249fc66f6f412ba089, you mention API changes, would it be possible to look into supporting the new version as well as the older one?

**Comment by pooler** [comment]
Since your request is not specific to the Litecoin port of Electrum, it should be directed upstream.
