### ISSUE TITLE
pool.sks-keyservers.net has been down for a while, can no longer follow instructions on website to verifiy Electrum-LTC binaries? 

### ISSUE THREAD

**Issue by DonW16** [pooler/electrum-ltc#277]
https://electrum-ltc.org/verifying-signatures.html

```
gpg --keyserver pool.sks-keyservers.net --recv-keys 0x6fc4c9f7f1be8fea 0xfe3348877809386c

gpg: keyserver receive failed: No name
```

pool.sks-keyservers.net also returns a 500 or nothing at all, maybe time to migrate PGP keys?

**Comment by pooler** [comment]
Public PGP keyservers synchronize with each other, so any well-functioning server should do. I changed the instructions to use the Ubuntu keyserver for now.
