### ISSUE TITLE
After Broadcasting Transaction - Unable to Close Window

### ISSUE THREAD

**Issue by tentious** [pooler/electrum-ltc#28]
I'm using a Macbook Pro.

After signing, then broadcasting the transaction, I'm unable to close the window and it doesn't go away on its own after receiving confirmations.

**Comment by pooler** [comment]
Are you using RC 2.6.0.1 or git master?

**Comment by tentious** [comment]
I'm using RC 2.6.0.1. 

>

**Comment by pooler** [comment]
Could you please test [RC 2.6.0.2](https://litecointalk.org/index.php?topic=18608.msg297281#msg297281)?

**Comment by tentious** [comment]
Yes, this is now fixed. Thanks for the help!
