### ISSUE TITLE
Electrum-LTC 2.9.3.1 Not Connected to Send

### ISSUE THREAD

**Issue by IndieJulian** [pooler/electrum-ltc#280]
Hi,

Electrum-ltc 2.9.3.1 on Macbook iOS 10.12.6 is not connected. Disable SSL and proxy [none] not working.

The device is unable to upgrade iOS for Electrum-LTC latest version. Thoughts?

**Comment by pooler** [comment]
As per the above, versions of Electrum and Electrum-LTC older than 3.3 can no longer connect to the network.

Unfortunately macOS 10.13 or newer is currently required (see https://github.com/spesmilo/electrum/issues/3685#issuecomment-508556343).

Version 3.3.8.1 might still work, and it should support macOS 10.12. You can download it [here](https://electrum-ltc.org/download/electrum-ltc-3.3.8.1.dmg).

**Comment by IndieJulian** [comment]
Thank you both! @pooler - the .dmg worked and LTC has been transferred from the old device. thank you very much
