### ISSUE TITLE
Wallet got hacked, all money taken

### ISSUE THREAD

**Issue by AnErrupTion** [pooler/electrum-ltc#287]
**First of all, I want to mention that I doubt this is really an Electrum LTC issue, but I still want to point it out because I don't really know what happened.**

Just about today when I'm writing this, my wallet got hacked by another one that has about 21 LTC, and has made no apparent transactions. To be clear, I have done nothing on my end (like catching a virus or something) that could've made that happen, so it's not about that. I have also downloaded Electrum LTC from the official website (electrum-ltc.org).

What happened is that the hacker first sent about 1 LTC, then successfully got all the money of my wallet (I had about 0.09 LTC in it, so they've got around 1.09 LTC). Here's the screenshot of all my transactions:

![image](https://user-images.githubusercontent.com/49339966/160202892-62087ae2-7a64-4a8d-8fd3-bd55adcb60a6.png)

For the last transaction, the wallet was ``ltc1qffuc32ut4v6fsgcrrlhldr29wyu2whjr35p9dz``, and it has about 21 LTC.

For the transaction before the last one, there were apparently 3 wallets:
```
LfA7A3wVdGysc4QXpsUvYaVUYvhcZnVE7j	     1.        
MMM2DYc9PVDEX44BUyZ1LXJKbZywqLEUof	     0.02126   
MFPgUUXKMY4Gygc4DnNdxnW2N3bjyP8VMC	    46.67764762
```

I have honestly no clue what happened. I would like some help here.

**Comment by koraycoding** [comment]
Did you encrypt your wallet before the lost your money? I use litecoin wallet all the time but keeping my money in paper wallets that I generated myself. When i need the transaction, just sweeping private keys into program. I recommend you to use this way so no one can reach your money.

P.S. Obviously don't keep your paper wallets in your pc.

**Comment by AnErrupTion** [comment]
I did encrypt my wallet. I did write the keys on paper instead digitally (I never put them digitally anyway)

**Comment by koraycoding** [comment]
You wrote the encryption password / private key on paper? In this case, I can't imagine who see that paper! Ask people who close to your computer. Someone stole your money but not hackers.

**Comment by AnErrupTion** [comment]
Nobody touched my computer except me! That's the thing.

**Comment by Margaret034** [comment]
Good day I got scammed too while trying to trade with this investor thanks to blackhathacker111 on telegram he helped me recover all my money

**Comment by GarettBill** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me recover all my funds,message him on telegram his telegram username is https://t.me/Blackhathacker111

**Comment by Margaret034** [comment]
> Nobody touched my computer except me! That's the thing. (Only my mother could've done it, but she doesn't know the password of my wallet anyway)

Same thing happened to me but thanks to blackhathacker111 who helped me get back my blockchain message him on telegram https://t.me/Blackhathacker111

**Comment by Bendy127** [comment]
So sorry about what happened same thing happened to me my wallet got hacked and about 0.9 btc was stolen thanks to Mr John a whitehathacker who helped me recover all of it message him on telegram too t.me/Whitehathacker217

**Comment by Bendy127** [comment]
So sorry about what happened same thing happened to me my wallet got hacked and about 0.9 btc was stolen thanks to Mr John a whitehathacker who helped me recover all of it message him on telegram too t.me/Whitehathacker217

**Comment by Bendy127** [comment]
So sorry about what happened same thing happened to me my wallet got hacked and about 0.9 btc was stolen thanks to Mr John a whitehathacker who helped me recover all of it message him on telegram too t.me/Whitehathacker217

K

**Comment by Blackhacker099** [comment]
So sorry about what happened same thing happened to me my wallet got hacked and about 0.9 btc was stolen thanks to  who helped me recover all of it message him on telegram too .https://t.me/badestha

**Comment by Frankly201** [comment]
I had lost some funds due to an airdrop scam too and it fucked me up luckily I got introduced to this hacker who helped me recover what was stolen from me hit him up on telegram::https://t.me/badestha

**Comment by Recovery0** [comment]
I had lost some funds due to an airdrop scam too and it fucked me up luckily I got introduced to this hacker who helped me recover what was stolen from me hit him up on telegram::https://t.me/badestha

**Comment by Tecmomoa** [comment]
Hi I am a tex who can fix this out, just contact me if you feel like.
