### ISSUE TITLE
release 4.2.x for freeze_utxo and aiorpcx updates

### ISSUE THREAD

**Issue by chappjc** [pooler/electrum-ltc#288]
Since you are keeping fairly well in sync with upstream Electrum, it would be helpful if a 4.2.x release could be made.  For me this would help with aiorpcx incompatibilities (0.22 supported upstream, but not at 4.0.9) as well as providing the `freeze_utxo` RPC that is absent in 4.0.9.

Apologies for making a request in a Github issue, but it does appear the [aiorpcx issue](https://github.com/pooler/electrum-ltc/issues/275) is resolved upstream so that could be resolved for end users with a new release.

Thanks for maintaining this project @pooler!

**Comment by pooler** [comment]
Version 4.2.2.1 is now available for download.
