### ISSUE TITLE
Can't import existing seed-phrase

### ISSUE THREAD

**Issue by apetrichkovich** [pooler/electrum-ltc#289]
**OS:** Windows 10
**Steps to reproduce:** Standard wallet -> I have already seed-phrase -> enter valid existed seed-phrase (this seed-phrase is from android LiteWallet app).
**Expected result:** Next button is available.
**Actual result:** Next button is not available for pressing.

**Comment by pooler** [comment]
Did you select BIP39 in Options?

**Comment by apetrichkovich** [comment]
Without BIP39 selection.

Now I have selected this option and Next button is available.
On the next step "**Script type & path**" I see "**Detect Existing Accounts** or **Select type of wallet address:** 1) legacy (p2pkh), 2) p2sh-segwit (p2wpkh-p2sh), 3) native segvit (p2wpkh). **You can replace path...** m/..."

What should I do on this step?

**Comment by pooler** [comment]
I suppose it depends on the type of address you were using in LiteWallet. If your addresses started with `L`, try selecting legacy (p2pkh) and `m/0'` for the path.

**Comment by apetrichkovich** [comment]
Wallet was created on Windows.
But there is something strange: in LiteWallet I see transaction and not zero balance; in Electrum-LTC there is no such address, transaction and balance is zero.
How does it possible when seed-phrase is the same?

**Comment by pooler** [comment]
You need to pick the right derivation path and type of address. I do not have experience with LiteWallet, but I know it follows the BIP39 standard, so this should be possible. If you are unsure about the derivation path of your wallet, you might want to get in touch with the LiteWallet team.

**Comment by apetrichkovich** [comment]
Hello.
Previously I've tried to import wallet without changing path.
Now I've changed path to `m/0'` with success.
Thank you very much :)
