### ISSUE TITLE
not verified

### ISSUE THREAD

**Issue by yangchunhe** [pooler/electrum-ltc#29]
my electrum-ltc of transactions Has been in a state of not verified，all transactions

**Comment by pooler** [comment]
What version of Electrum-LTC did you use to create the transactions, and what version are you using now (if different)?

**Comment by yangchunhe** [comment]
Latest Version: 2.6.1.1,yes, i create some transactions, but all transactions show not verfifed on osx,win10 is ok

**Comment by pooler** [comment]
Could you please provide the transaction ids, as well as a screenshot of the main Electrum-LTC screen?

**Comment by yangchunhe** [comment]
now is ok ,thanks a lot!  I  keeped electrum-ltc connect network more than one hours ， then is ok

**Comment by knocte** [comment]
I have this issue. @yangchunhe is "waiting" just the recommended thing to do?

**Comment by knocte** [comment]
sorry, I meant to highlight @pooler here :)

**Comment by pooler** [comment]
@knocte What is your transaction's id?

**Comment by knocte** [comment]
@pooler and just when I was going to provide you the IDs, it became green :) So it seems just a matter of wating.
