### ISSUE TITLE
Tried to Send and Transaction is Unconfirmed after days . . . 

### ISSUE THREAD

**Issue by johnnythinker** [pooler/electrum-ltc#30]
Hello, 
I'm running v 2.6.1.1 and tried to send some coin out. The transaction is still unconfirmed and has not shown up in the blockchain. I have loaded the wallet on another computer but same thing. 
What can I do to cancel the transaction? 
Thanks, 
JT

**Comment by pooler** [comment]
Did you create this transaction in 2.6.1.1, or did you use an older version and then upgrade?

Could you please post the transaction ID?

**Comment by johnnythinker** [comment]
Thanks for your help. It was the same version. 

cbe9af0386703539e900c026e16a28610f3dbef5850518de15577930f997e794

**Comment by johnnythinker** [comment]
Wow, not sure what you did but it just started working. If that was you thanks a bunch.

**Comment by pooler** [comment]
No, I did nothing. I only checked it against my server's logs, and what I found is that it appears to somehow have a non-canonical signature.
Are you sure that the transaction went through? It still doesn't show on block explorers. Did it change ID?
