### ISSUE TITLE
Provide release tarballs with git submodules included.

### ISSUE THREAD

**Issue by amano-kenji** [pooler/electrum-ltc#301]
github doesn't generate tarballs with git submodules. Repository maintainers have to manually add tarballs with git usbmodules to releases.

**Comment by pooler** [comment]
Are you using the 4.2.2.1 tarball from [electrum-ltc.org](https://electrum-ltc.org)?

**Comment by amano-kenji** [comment]
https://electrum-ltc.org/download/Electrum-LTC-4.2.2.1.tar.gz is already built.

On gentoo linux, everything is built from source.

**Comment by pooler** [comment]
> https://electrum-ltc.org/download/Electrum-LTC-4.2.2.1.tar.gz is already built.

I'm honestly not sure what you mean. That's the Python source code.

**Comment by amano-kenji** [comment]
https://electrum-ltc.org/download/Electrum-LTC-4.2.2.1.tar.gz looks different from https://github.com/pooler/electrum-ltc

Can a package build script build and install electrum-ltc from https://electrum-ltc.org/download/Electrum-LTC-4.2.2.1.tar.gz ?

**Comment by pooler** [comment]
> https://electrum-ltc.org/download/Electrum-LTC-4.2.2.1.tar.gz looks different from https://github.com/pooler/electrum-ltc

They are different. One is the distribution tarball for version 4.2.2.1, the other is the current master branch of the Git repository.

> Can a linux distribution package build script build and install electrum-ltc from https://electrum-ltc.org/download/Electrum-LTC-4.2.2.1.tar.gz ?

I don't see why not.

**Comment by amano-kenji** [comment]
If there is a problem, I'll open a new issue.
