### ISSUE TITLE
Upgrading the wallet?

### ISSUE THREAD

**Issue by briannyeko** [pooler/electrum-ltc#31]
When will you upgrade the wallet? and when will you port the wallet to iOS and android?

**Comment by pooler** [comment]
We are already in sync with upstream. The release of a 2.6.4.x version got delayed because of a major bug in Electrum 2.6.4 which was only fixed a few days ago. If no other major issues show up, I will probably make a new release in a couple days. Regarding kivy, @thrasher- is looking into it.

**Comment by pooler** [comment]
Electrum-LTC 2.6.4.2 can now be downloaded from the official website.
