### ISSUE TITLE
send all balance

### ISSUE THREAD

**Issue by MU12351235** [pooler/electrum-ltc#311]
Hello, I hope you are well
I am working on a Litecoin project
I want to send all my balance but I don't know how?
thanks for help

**Comment by DrrDino** [comment]
Message blackhathacker111 on telegram to help you with that https://t.me/Blackhathacker111

**Comment by MU12351235** [comment]
please help me

**Comment by pooler** [comment]
Sorry but this is a bug tracker, not a help center. If you need assistance, you could ask on the [r/litecoin](https://www.reddit.com/r/litecoin/) subreddit or on a forum (just never share sensitive data with others, obviously).

**Comment by MU12351235** [comment]
thanks.
