### ISSUE TITLE
can not make new install

### ISSUE THREAD

**Issue by pdmk** [pooler/electrum-ltc#32]
Hi I downloaded this app, but didnt know how to work with it...

So at first install I chosed the wallet type where you need 4 master keys.. and that was wrong.
I tried the install again, but always got the screen where I need to put 4 master keys (1 is generated on screen).
I tried to delete the hidden folder .electrum and restart, but that didnt help. Always when I start electrum app it puts me directly to that screen where I need to put 4 master keys.

I want to create new wallet, but there is no option for this, the only thing I can do is quit app. Even if I press cancel it quits the app.

Any idea how to solve this?

Thank you

**Comment by pooler** [comment]
What operating system are you running?

**Comment by pdmk** [comment]
sorry, OSX 10.11.4, all updated

**Comment by pooler** [comment]
Try deleting the folder `~/.electrum-ltc` and starting afresh. (I'm assuming this is a new installation of Electrum-LTC and that you don't have any coins in your wallets.)

**Comment by pdmk** [comment]
that worked! thanks for help
