### ISSUE TITLE
Coins not received

### ISSUE THREAD

**Issue by wfdjr** [pooler/electrum-ltc#33]
Hello sent some LTC coins from my LTC wallet to my new electrum LTC wallet the first coins (55 ea) went through to my new electrum wallet in 4 mins the second batch (40,8 ea) did not show up at my electrum wallet and it has been several hours. What happened? Please advise.

**Comment by pooler** [comment]
What client did you use to make the two transactions? (Please specify the version as well.)
Could you post the transaction ids?

**Comment by wfdjr** [comment]
Hello, thanks for looking into this, here is the info from my LTC wallet- QT version 8.5.1. The first transaction went through fine, this one below has not shown up yet


Date: 6/4/2016 14:15
To: LTsBFXRFiHxnV33ooYgMC9VPnTMNxfvsPU
Debit: -40.7936 LTC
Transaction fee: -0.02 LTC
Net amount: -40.8136 LTC
Transaction ID: 93c6819e47d4e90675cc1321b9e7799934a5d1adcba1c72da7cabedc7ee075b5

Thanks Bill

**Comment by pooler** [comment]
You used an outdated version of Litecoin Core from before the soft fork, so it is possible that you produced an invalid transaction. You need to [upgrade](https://litecoin.org).

**Comment by wfdjr** [comment]
I tried to update but Norton is saying the update is unsafe and is removing the exe file.

Also will updating allow me to retrieve the lost coins?

Please advise

Thanks Bill

**Comment by pooler** [comment]
There are no lost coins, if the transaction is invalid and hasn't been picked up by the network, the coins never moved.

Regarding your antivirus issue, it's almost certainly a false positive, so if possible I would simply whitelist the file. After having verified the digital signature, of course. I'm afraid I cannot provide further assistance with this.

**Comment by wfdjr** [comment]
Thank you very much for your help. I installed the update and the coins were there and never sent as you said. Resent the coins and they were received. Again thank you very much, I really appreciate your help.

Bill

**Comment by pooler** [comment]
You're welcome!
