### ISSUE TITLE
wallet corrupted,cant withdraw funds because someone hacked me and tried to steal

### ISSUE THREAD

**Issue by Bojan311** [pooler/electrum-ltc#330]

**Comment by pooler** [comment]
Duplicate of #332

**Comment by Bojan311** [comment]
But this is not completed,i cant solve this problem bruhhhh

pon, 21. okt 2024. 14:33 pooler ***@***.***> je napisao/la:

**Comment by pooler** [comment]
> But this is not completed,i cant solve this problem bruhhhh

If this is the same problem as #332, please use that thread. Otherwise, you should clarify why this is a separate issue.

**Comment by Bojan311** [comment]
I still wait for support to send me funds she told me she can send i dont
know why dont sending

pon, 21. okt 2024. 14:46 pooler ***@***.***> je napisao/la:

**Comment by pooler** [comment]
> I still wait for support to send me funds she told me she can send i dont know why dont sending

There is no "support". Do not trust anyone posing as official support for Electrum-LTC, they will try to scam you.

**Comment by Bojan311** [comment]
Where to contact then?

pon, 21. okt 2024. 15:07 pooler ***@***.***> je napisao/la:

**Comment by pooler** [comment]
> Where to contact then?

There is no one to contact. I try to help when I can (see other thread), but Electrum-LTC is free software, it comes with no guarantees and no dedicated support.

**Comment by Bojan311** [comment]
Can i contact you somewhere and give u details to try to solve the
problem,i will give you 20% of funds.

pon, 21. okt 2024. 15:21 pooler ***@***.***> je napisao/la:

**Comment by pooler** [comment]
> Can i contact you somewhere and give u details to try to solve the problem,i will give you 20% of funds.

No, sorry.
