### ISSUE TITLE
update bundled dependency of python-trezor to at least version 0.6.13

### ISSUE THREAD

**Issue by prusnak** [pooler/electrum-ltc#34]
... for windows builds

this fixes issues with firmware 1.3.6 (it is unusable with older python-trezor) on windows

**Comment by pooler** [comment]
I have just updated the Windows binaries of version 2.6.4.2 to include python-trezor 0.6.13. Could you please check them out and confirm that everything works as expected?

**Comment by prusnak** [comment]
cc @martin-lizner

**Comment by martin-lizner** [comment]
Hi, seems new binary is working with 1.3.6 and also 1.3.5 fw. However, I didnt do full testing with signing txs.

I suggest bumping version of 2.6.4.2.

**Comment by pooler** [comment]
@martin-lizner Hi! Here we're specifically interested in message signing, not transaction signing. Did you test that? (You could use [this tool](https://www.litecoinpool.org/verifymessage) if you don't have easy access to a Litecoin Core installation.)

**Comment by martin-lizner** [comment]
well this does not look so positive, 1.3.5 signs but fails to verify, 1.3.6 says "Electrum cannot pair..."

**Comment by prusnak** [comment]
Message signing for altcoins was fixed in 1.3.6, so failing in 1.3.5 and older is expected.
No idea what the new error means.

As the main issue with version update of python-trezor is fixed. I am closing this now. Feel free to create other tickets for outstanding issues.
