### ISSUE TITLE
LTC In Limbo

### ISSUE THREAD

**Issue by Joannou1** [pooler/electrum-ltc#36]
I recently restored an old backup of a crashed drive and tried to open my default_wallet file with the latest release (2.6.4.2).
Unfortunately, it seems horribly broken in the sense that all the transactions appear as "0.".
I checked my address and see that I have 135 LTC in there, but Electrum shows 0.

![88595](https://cloud.githubusercontent.com/assets/997747/17351775/46f2dbbe-58e6-11e6-99b3-769363e9097b.png)

http://explorer.litecoin.net/address/18e8rntg4kGscxbvMBG2xscwMGc3yBmmNJ

If I start it up again after copying the default_wallet file, it says that the wallet is in watching-only mode.
I don't know what to do, are these coins gone for good?

It's worth noting, the wallet I am restoring was last used on 1.9.8.6 on Windows 7.
I tried with that version on my laptop, and the program immediately closes, same on win 10.

**Comment by pooler** [comment]
Please try restoring your wallet from seed.

**Comment by Joannou1** [comment]
I found a slightly older backup that restored correctly without the need for a seed.
All is well with the world.

Not sure what was up with that other wallet file though...
