### ISSUE TITLE
Doesn't work with new firmwares of Trezor hardware wallet

### ISSUE THREAD

**Issue by aurics** [pooler/electrum-ltc#37]
for reference :  

https://github.com/spesmilo/electrum/issues/1846

it's fixed in Electrum BTC

**Comment by pooler** [comment]
That specific issue should be fixed in this repo as well.
Are you running a specific version of Electrum-LTC, or from git master? On what OS?

**Comment by aurics** [comment]
Hi, I'm running electrum-ltc-setup-2.6.4.2.exe from the official web site
on windows 8.1 x64

**Comment by pooler** [comment]
Did you download it recently or before June 25? If you're not sure try reinstalling it, as the Windows build of 2.6.4.2 was updated at a certain point exactly because of this.

**Comment by aurics** [comment]
I have downloaded it long time ago, i will try to reinstall

**Comment by aurics** [comment]
Yep now works, thanks, it's little confusing with the same number of the version
