### ISSUE TITLE
Electrum LTC - server lagging

### ISSUE THREAD

**Issue by DataWest** [pooler/electrum-ltc#38]
I am trying to run this software after extended period of time where I didn't use it, I have left it running for weeks now and it always says server lagging 530481 blocks.
Please help me, I cannot access litecoins in the backup.

**Comment by pooler** [comment]
Have you tried connecting to a different server?

**Comment by DataWest** [comment]
I have it set to auto select, I did try manually to different server but that was random selection and none helped that I tried.

**Comment by pooler** [comment]
Assuming you are on the latest version, try this: close Electrum, make a backup copy of your data directory, including your wallets, then delete the folder (equivalently, move it somewhere safe) and restart Electrum, Let it sync, then restore your wallets from seed.

**Comment by DataWest** [comment]
That was unsuccessful, I managed to find a older version 2.6.0.1 and I started that and I had a green connected icon for a second or two and my litecoin balance showed, then it switched to red but my balance stayed and it is also now saying server is lagging 636423 blocks. I will let it run overnight and see what happens. The seed code is the same and that result in saying there was no balance on v 2.6.4.2 but I would guess because it was not synced.

**Comment by pooler** [comment]
Why 2.6.0.1? Downgrading Electrum is generally a bad idea. Please only use the latest version.

Did you follow this procedure exactly?

* Close Electrum.
* Backup the data folder. (Which OS are you on, and where is the folder located?)
* Delete the data folder.
* Start Electrum.
* Let it synchronize.
* Restore your wallet using the seed phrase.

**Comment by DataWest** [comment]
I created a new electrum folder with the latest version and loaded the my wallet and it doesn't show any balance and does not sync. Therefore I tried a older version and that does show the balance, for awhile I was believing I lost my coins until I loaded the older version.

Next I found a data folder under local roaming folder in user profile, deleted it, restarted the latest version,  loaded a backup wallet, seen a litecoin balance for a second and then that went away and now its again the same message server lagging. The older version did not resolve server lag overnight. I will leave the newer version for the day and see how that goes.

**Comment by pooler** [comment]
I'm assuming you're on Windows, so the folder you should have backed up and deleted is `\Users\YourUserName\AppData\Roaming\Local\Electrum-LTC` (as per the FAQ on the website). Please check if that's the one you deleted.
When you restart Electrum, it should show you the Install Wizard. Try creating a new wallet and see if it manages to sync in that case.

**Comment by DataWest** [comment]
Yes that has worked, I am very grateful for your support, I was getting kinda concerned.
Thank you,
Dale

**Comment by pooler** [comment]
You're welcome.
