### ISSUE TITLE
[Feature request] Chocolatey support?

### ISSUE THREAD

**Issue by Kristinita** [pooler/electrum-ltc#39]
I think it would be good if the Electrum Litecoin could be loaded using Chocolatey — Windows package manager — as [Electrum and other purses cryptocurrency](https://chocolatey.org/packages?q=cryptocurrency).

Thanks.

**Comment by pooler** [comment]
All cryptocurrency-related Chocolatey packages appear to be maintained by @dtgm. Maybe you could ask him if he'd be so kind to add a package for Electrum-LTC as well.

**Comment by AdmiringWorm** [comment]
@pooler I've created chocolatey packages for your software, and they are currently going through the moderation process.
The actual packages are:
[Meta package](https://chocolatey.org/packages/electrum-ltc/2.6.4.2)
[Installer based](https://chocolatey.org/packages/electrum-ltc.install/2.6.4.2)
[Portable/Standalone](https://chocolatey.org/packages/electrum-ltc.portable/2.6.4.2)

The source for these packages is also available at my chocolatey package repository (new versions are checked each day):
https://github.com/AdmiringWorm/chocolatey-packages/tree/master/automatic

Please don't hesitate if at some point in the future you wish to maintain those packages yourself, or if you have anything you wish to have changed.

**Comment by pooler** [comment]
@AdmiringWorm Thank you!
