### ISSUE TITLE
Error creating binaries

### ISSUE THREAD

**Issue by psionin** [pooler/electrum-ltc#40]
On a Debian 8 machine

```
user@sys-smartcoin:~/electrum-ltc$ ./contrib/make_packages
version 2.7.12
Traceback (most recent call last):
  File "./contrib/make_packages", line 28, in <module>
    f, pathname, descr = imp.find_module(module)
ImportError: No module named aes
```

**Comment by pooler** [comment]
Did you install dependencies?

**Comment by psionin** [comment]
I went through the instructions starting with installing, and the setup.py install seemed to run fine - [http://pastebin.com/c8YA5LjZ](http://pastebin.com/c8YA5LjZ). Doing the development version.

**Comment by pooler** [comment]
Your log says slowaes is already installed under `/rw/usrlocal/lib/python2.7`. If you run python2, can you `import aes`?

**Comment by psionin** [comment]
I copied that log after I ran the command again (the first run may have been a fresh installation). Yes, when I `import aes`, there are no errors.

**Comment by psionin** [comment]
I guess there is some kind of issue with `imp.find_module(module)`.

I solved this by moving the downloaded `.egg` packages from `/usr/local/lib/python2.7/dist-packages` to the `contrib` folder and extracting them there with `unzip` and then running `make_packages` again. (e.g., `sudo unzip slowaes-0.1a1-py2.7.egg`)
