### ISSUE TITLE
Updating of downloads page/list

### ISSUE THREAD

**Issue by RustyNomad** [pooler/electrum-ltc#41]
Just checked the downloads page at https://electrum-ltc.org/download/ and the latest version available from there is 2.6.4.2

Will this page be updated with the latest version(s) or can they be downloaded from another site?

**Comment by pooler** [comment]
The latest released version of Electrum-LTC is 2.6.4.2. When a new version will be released it will be made available at https://electrum-ltc.org/.

**Comment by RustyNomad** [comment]
Thanks
