### ISSUE TITLE
New builds?

### ISSUE THREAD

**Issue by RustyNomad** [pooler/electrum-ltc#42]
Any indication of when new builds will be released? The latest on the download page was for version 2.6.4.2 which was released around June of 2016, almost a year ago.

**Comment by pooler** [comment]
I'd stick with 2.6.4.2 for the time being. Especially given that, to my knowledge, there is nothing wrong with it. Electrum 2.7 introduced quite a few new bugs and, as far as I can tell, no new features that would be particularly useful to Litecoin users. Therefore, I'd rather wait for 2.8 to stabilize before releasing a new official version.

**Comment by RustyNomad** [comment]
Thanks, will wait for 2.8
