### ISSUE TITLE
Segmentation fault when opening the QR code scanner on Tails 3.0 (tried Electrum BTC 2.8.2 and 2.8.3 same problem, 2.7.18 OK)

### ISSUE THREAD

**Issue by JazzTp** [pooler/electrum-ltc#50]
Electrum-LTC beta 2.8.3.2 on Tails 3.0. 

**Tools | Load transaction | From QR code => segmentation fault**. I don't see the QR code scanner window appear, just the Electrum-LTC window disappear leaving the error on the terminal window from which I had launched it.

I tried with two different webcams, nothing changes.

**The QR code scanner works fine in Electrum BTC** (with both webcams), **possibly launching it the same way as Electrum BTC does could solve the issue.**

**On Linux Ubuntu 16.04, Electrum-LTC opens the QR code scanner just fine** (with both of these webcams).

**This was also not happening on Tails 2.12** where I was able to spend LTCs from this wallet using screen-to-webcam communication with the cold storage part.

(However, on Tails 2.12 there was another problem not present on Tails 3.0, reported in issue #48.)

### New warnings

Electrum-LTC is showing some warnings on Tails 3.0 that I wasn't seeing on Tails 2.12 (Electrum BTC too).

Here they are (the segmentation fault error did not happen unless I tried to open the QR code scanner):

```
Warning: ltc_scrypt not available, using fallback
Gtk-Message: Failed to load module "gail"

** (python2:20455): WARNING **: (bridge.c:993):atk_bridge_adaptor_init: runtime check failed: (root)
_IceTransSocketUNIXConnect: Cannot connect to non-local host localhost.localdomain
_IceTransSocketUNIXConnect: Cannot connect to non-local host localhost.localdomain
Qt: Session management error: Could not open network socket
libpng warning: iCCP: known incorrect sRGB profile
Segmentation fault
```

**Comment by pooler** [comment]
What version of Electrum (for Bitcoin) did you use? You should test the latest git master.

**Comment by JazzTp** [comment]
Hi,

Hi reported that Electrum for BTC works fine.

(Always getting it from electrum.org. Using 2.7.18 - not 2.8.2 and 2.8.3
because of an issue I reported, I'm on my phone right now in the middle of
something can't search the issue number sorry, transaction details window
showing bad info for v2 transactions, it was immediately linked to another
previously reported issue, something like possible regression in hash
calculation.)

**Comment by pooler** [comment]
I'm afraid knowing that Electrum 2.7.18 works fine is not very useful, as Electrum-LTC 2.8.3.2 is based on a much more recent version of Electrum. (Notably missing from 2.7.18 is d99855f.) This is important because it seems unlikely that this issue is specific to the Litecoin port, and as a rule of thumb if a bug is present upstream it should be fixed there first.

**Comment by JazzTp** [comment]
Oh I see why you asked now, sorry.

I could easily test the current official release Electrum BTC 2.8.3 on
Tails 3.0 (in a short while), would that be useful or is Electrum LTC based
on a different more recent version? (I won't be able to test the git
development version I'm afraid.)

**Comment by pooler** [comment]
git master would be best, but 2.8.3 may also be useful.

**Comment by JazzTp** [comment]
(Could pass on my pc in a _hurry_ or will be late for a job.)

Electrum BTC 2.8.2 as 2.8.3 segmentation fault on Tails 3.0 (with both webcams for what it might matter, probably nothing at all).

```
amnesia@amnesia:~$ cd /home/amnesia/Electrum-2.8.3 ; ./electrum
Gtk-Message: Failed to load module "gail"

** (python2:15396): WARNING **: (bridge.c:993):atk_bridge_adaptor_init: runtime check failed: (root)
/media/amnesia/watchOnly/BTCprepAndLaunchElectrum_2.8.3.sh: line 29: 15396 Segmentation fault      ./electrum
amnesia@amnesia:~$ cd Electrum-2.8.3/
amnesia@amnesia:~/Electrum-2.8.3$ ./electrum 
Gtk-Message: Failed to load module "gail"

** (python2:18311): WARNING **: (bridge.c:993):atk_bridge_adaptor_init: runtime check failed: (root)
Segmentation fault
amnesia@amnesia:~/Electrum-2.8.3$ 
```

```
amnesia@amnesia:~$ cd /home/amnesia/Electrum-2.8.2 ; ./electrum
Gtk-Message: Failed to load module "gail"

** (python2:18358): WARNING **: (bridge.c:993):atk_bridge_adaptor_init: runtime check failed: (root)
/media/amnesia/watchOnly/BTCprepAndLaunchElectrum_2.8.2.sh: line 29: 18358 Segmentation fault      ./electrum
amnesia@amnesia:~$ cd Electrum-2.8.2/
amnesia@amnesia:~/Electrum-2.8.2$ ./electrum 
Gtk-Message: Failed to load module "gail"

** (python2:21195): WARNING **: (bridge.c:993):atk_bridge_adaptor_init: runtime check failed: (root)
Segmentation fault
amnesia@amnesia:~/Electrum-2.8.2$
```

I actually manually pasted at the top the last two commands the calling script performs, I have scripts ready for each electrum version I tried... keep Electrum and scripts on a pendrive, boot Tails from DVD (I only install Tails on pendrive with "Persistence" active for the offline cold storage part).

The script simply symlinks a folder .electrum_versionNumber from the pendrive into the (amnesic-on-RAM) home dir /home/amnesia then extracts electrum into the same home dir, cd's into the electrum folder and launches ./electrum, thus avoiding to use the version coming with Tails (it's usually an older one).

Months ago I wanted to build electrum from github but I found myself pretty clueless than saw main dev recommending official version from electrum.org and dropped that idea, only followed issues when I could to help answer on simple stuff I knew or to report some problem.

(But you could grab Tails from tails.boum.org, torrent is probably the fastest method.)

**Comment by pooler** [comment]
Thanks for testing. If I understand correctly, Electrum 2.8.3 is also affected, so I think you should open a ticket upstream.

**Comment by JazzTp** [comment]
Right (going to do it in 1-2 hours maximum probably earlier).

**Comment by JazzTp** [comment]
P.S.: you're welcome, thanks **to you all** for the great and huge job you're doing.

Opened issue for Electrum BTC [https://github.com/spesmilo/electrum/issues/2527](https://github.com/spesmilo/electrum/issues/2527)

**Comment by JazzTp** [comment]
P.S.: you're welcome, thanks **to you all** for the great and huge job you're doing.

Opened issue for Electrum BTC [https://github.com/spesmilo/electrum/issues/2527](https://github.com/spesmilo/electrum/issues/2527)

**Comment by JazzTp** [comment]
My statement "none has this issue on Tails 2.12" could be false, on Electrum BTC 2.8.3.2 I've just experienced the segmentation fault on Tails 2.12, trying to open the QR code scanner. There were no warnings in the terminal window before the segmentation fault error.

**Comment by pooler** [comment]
Closing as the fix from upstream has been merged.
