### ISSUE TITLE
MD5 hash checksums do deviate for all OSX downloads on electrum-ltc.org!

### ISSUE THREAD

**Issue by robinsonreichel** [pooler/electrum-ltc#51]
What is the problem?
Read about trojans connected to those downloads...

**Comment by pooler** [comment]
I just checked 3 files at random and all the hashes matched. What files did you check, and what hashes did you get?

**Comment by robinsonreichel** [comment]
i am totally new to it.
i did follow a routine i found on the internet for OSX Terminal.
i downloaded the 2.6.4.2.dmg and the .zip and checked them by "shasum " command, dragged the dmg to the terminal and executed.
i have attached some screenshots

**Comment by pooler** [comment]
> i have attached some screenshots

I'm afraid GitHub's issue tracker ignores email attachments.

**Comment by robinsonreichel** [comment]
dang, i'll paste some text.
chrome reveals:
# MD5 hash
a7c7dc6f26d7ffc09399ff733e91a9b9  Electrum-LTC-2.6.4.2.dmg
# SHA-256 hash
38dcf0c7cb49a6bcb5daa350c0b225b4ca464263d78a2d28fb87eb5b9ede8e7b  Electrum-LTC-2.6.4.2.dmg

terminal brings up:

Tests-MBP:~ RR$ 
Tests-MBP:~ RR$ shasum /Volumes/This\ is\ it\!\ El\ Capitan/Users/Test/Downloads/Electrum-LTC-2.6.4.2.dmg 
aeebe76c42b842c44257f9919d8404c08b0000e7  /Volumes/This is it! El Capitan/Users/Test/Downloads/Electrum-LTC-2.6.4.2.dmg
Tests-MBP:~ RR$ shasum /Volumes/This\ is\ it\!\ El\ Capitan/Users/Test/Downloads/Electrum-LTC-2.6.4.2\ \(1\).dmg 
aeebe76c42b842c44257f9919d8404c08b0000e7  /Volumes/This is it! El Capitan/Users/Test/Downloads/Electrum-LTC-2.6.4.2 (1).dmg

???
i don't get the concept.

**Comment by pooler** [comment]
By default `shasum` computes SHA-1 hashes. Use `shasum -a 256` to compute SHA-256 hashes, or use `md5` to compute MD5 hashes.

**Comment by robinsonreichel** [comment]
Thx a gazillion times! :)

**Comment by robinsonreichel** [comment]
THX
