### ISSUE TITLE
Extended master keys use Bitcoin specific version bytes (xprv/xpub) instead of Litecoin (Ltpv/Ltub)

### ISSUE THREAD

**Issue by m-x-m** [pooler/electrum-ltc#52]
Extended master keys exported by Electrum-LTC use the Bitcoin network specific version header (0x0488B21E/0x0488ADE4 -> xpub/xprv) instead of the Litecoin network header (0x019da462/0x019d9cfe -> Ltub/Ltpv). This can cause problems when importing the master keys in other software.

To reproduce: 
1. create a new standard wallet named wallet_temp
2. grep '"xpub"' ~/.electrum-ltc/wallets/wallet_temp
should output the wallet's master public key. If the key starts with "xpub", then it's a Bitcoin extended key and there is a problem. 

The problem is caused by unpatched Electrum code in lib/bitcoin.py . As this file has changed a fair bit recently, the problem has moved around, but it always boils down to the use of the wrong set of header constants. In the current master branch, for example, the functions xprv_header() and xpub_header() currently reference the wrong (Bitcoin) set of version byte constants instead of the _ALT (Litecoin) ones. 

Secondly, is there a reason for using two sets of version constants at all (XPRV_HEADER/XPRV_HEADER_ALT etc)? As far as I can tell, the Bitcoin-specific constants are 100% useless in the Litecoin context and should be safe to overwrite, which would probably fix the problem across the board with a smaller diff.

**Comment by pooler** [comment]
Officially Litecoin uses the same BIP32 prefixes as Bitcoin (see [here](https://github.com/litecoin-project/litecoin/blob/v0.13.2.1/src/chainparams.cpp#L130)). This is on purpose, as it makes sense to generate addresses for multiple cryptocurrencies from a single master key.

The Ltub/Ltpv prefixes were independently made up by the author of the website bip32.org before BIP32 was even discussed by the Litecoin development team. As far as I know they were never officially supported, but unfortunately many developers who believed they were official used them in their software, contributing to the confusion.

**Comment by m-x-m** [comment]
Oh - I wasn't aware of that, but it does indeed make sense. Thanks for the clarification!

**Comment by yashikada** [comment]
@pooler sorry if I write in old issue, is there a way to import Ltpv key in electrum-ltc? Or is there a way for generate account bip49 xprv from mnemonic?
html file bip49 doesn't support bip49 xprv but only Ltpv, so I can't import in electrum-ltc, as temporary workaround I imported single private keys, but I'd like use a master key xprv.
