### ISSUE TITLE
App Will Not Open

### ISSUE THREAD

**Issue by FruitLoops24** [pooler/electrum-ltc#57]
I am having an issue with opening Electrum LTC after installation on windows. After installation, it seems the shortcut and file in the Electrum-LTC folder is .exe and does not open.

**Comment by pooler** [comment]
What version of Windows, and what version of Electrum-LTC?

I just tested `electrum-ltc-2.8.3.5-setup.exe` on Windows 7, and after the installation the shortcut in the Electrum-LTC folder worked just fine.
