### ISSUE TITLE
Connection Failed

### ISSUE THREAD

**Issue by altaegonerd** [pooler/electrum-ltc#58]
When opening Electrum-LTC app (with Trezor plugged in) I get a **"Connection failed"** error message.

Cannot send (or receive) any LTC.

Thoughts?

**Comment by pooler** [comment]
You didn't mention which version you are using, but this seems relevant: https://bitcointalk.org/index.php?topic=1984293.0
I would try recreating the wallet(s) in question as suggested in the last post by nerioseole (make a backup first, just in case)?
