### ISSUE TITLE
Litecoin version will not sweep private key from cold storage.

### ISSUE THREAD

**Issue by phuzzyday** [pooler/electrum-ltc#59]
I have a paper litecoin wallet from a long time ago, and I would like to recover the funds from it.  When I paste the (correct) key into the dialog window for sweeping private addresses, the next button stays greyed out no matter what I do.  Pasting the same key allows me to check the balance on the website, so it is accurate.

I can't find any other way to recover these funds!  Help would be great!

**Comment by pooler** [comment]
What version are you using? I was unable to reproduce your issue with 2.8.3.5.

Is your private key in WIF format? It should be either 51 characters long and start with a '6', or 52 characters long and start with a 'T'.

**Comment by phuzzyday** [comment]
Oh my goodness...  I goofed.  I had my keys mixed up.  Can we delete this stupidity?  It's all good.
