### ISSUE TITLE
electrum-ltc --testnet seems to be on the wrong testnet version

### ISSUE THREAD

**Issue by snitko** [pooler/electrum-ltc#60]
Just sent some testnet litcoins from my litcoin-qt wallet (testnet) to electrum-ltc also run on testnet. Unfortunately, they didn't show up. My guess is, electrum-ltc uses older testnet (v3?) while litecoin-core is currently on v4. Should it be fixed, perhaps?

**Comment by pooler** [comment]
Electrum-LTC already uses testnet v4, but it looks like the only testnet server got stuck for some reason. It should be fixed now, please try again.

**Comment by snitko** [comment]
Yep, can confirm, fixed. I see the transaction now.

**Comment by sleemanj** [comment]
Is there a problem with the testnet server again or am I doing something wrong?  Currently more than 12 thousand blocks behind I think, electrum-ltc 2.9.3.1 freshly installed today, details are in the screenshot...

![chic41](https://user-images.githubusercontent.com/207209/33511053-52c54fa4-d779-11e7-97bb-7bddba696377.png)

https://www.reddit.com/r/litecoin/comments/7gzgbq/electrum_linux_testnet_not_receiving/

**Comment by pooler** [comment]
@sleemanj: the database of electrum-ltc.bysh.me got corrupted. I've now updated ElectrumX to the latest version and reindexed from scratch. I'll try to contact the operator of the other server as well.

More testnet servers wouldn't hurt.
