### ISSUE TITLE
how compile apk for android ?

### ISSUE THREAD

**Issue by mraksoll** [pooler/electrum-ltc#62]
How compile apk for android , i compile it but it not work ? what depends need where i can read about it ?

**Comment by pooler** [comment]
Sorry, Android is not currently supported.

**Comment by mraksoll** [comment]
I ask how compile it, no mater supported it or not, it most work on android. If work  original electrum

**Comment by mraksoll** [comment]
What the latest version is can be compiled ?

**Comment by mraksoll** [comment]
It's compile , but problem with lib's

**Comment by pooler** [comment]
@mraksoll, sorry, I can't help you. I've never even tried to build the APK.

**Comment by mraksoll** [comment]
But it building succes ) but nit load lib's need find where problem and i can make doc for build it with debian for android. But for what reason it's not add lib's python on apk, or i use no compatible version of some deps

**Comment by mraksoll** [comment]
![111111](https://user-images.githubusercontent.com/21091190/29458982-6bb8c4f2-842a-11e7-9739-1b90a0d821f1.jpg)
