### ISSUE TITLE
Bought LTC but accidently send it to my BTC electrum wallet

### ISSUE THREAD

**Issue by klapinga** [pooler/electrum-ltc#71]
Hi guys,

So here is the story.
 I made a pretty stupid mistake. I have two electrum wallets. 1 wallet for bitcoins and 1 wallet for litecoins. I bought a bunch of litecoins from this company: https://www.litebit.eu/en
During the buying proces I used the receiving adress of my bitcoin wallet instead of my litecoin wallet.
The order is processed and confirmed but offcourse I didnt receive the litecoin because I used the wrong receiving adress.
Is there a way to get my litecoin to my litecoint electrum wallet?

I already came accross this post, in which pooler gave some pretty awesome help.
https://github.com/pooler/electrum-ltc/issues/68#issuecomment-328260191

I tried to follow the steps that were mentioned but for some reason i wont get it to work.
@Pooler if you would be so kind to go over it one more time with me. I would appreciate that very much.

**Comment by pooler** [comment]
Could you please describe in detail the steps you followed and the results you observed?

**Comment by klapinga** [comment]
Ok, so i followed your instruction:

> You should have mentioned this earlier. Two-factor authentication is a service provided by TrustedCoin (see here), and they do not support Litecoin, which is why this option isn't present in Electrum-LTC.
Now, the problem is that 2FA seeds are a special variety that isn't supported by Electrum-LTC (for the reason above). It should still be possible to recover the coins, I'm just not entirely sure how without writing ad-hoc code. Here is what I would try. First of all, in Electrum for Bitcoin, make a new wallet restoring from your 2FA seed, and when asked select to disable TrustedCoin. Do not enter a password. Then, close Electrum and open the wallet file you just created in a text editor. You will find 3 xpub and 2 xprv addresses. Open Electrum-LTC and create a new multi-sig wallet with a 2-of-3 scheme. Use the first xprv address and the other two xpub addresses. This should give you a wallet with the right addresses (use the converter to check). Finally, make a wallet for the second signer using the second xprv and the other two xpub addresses.> 


So i created the new wallet. Open the filet in text editor and found the 3 xpub and 2 xprv adresses. I opend the electrum LTC wallet and started creating a new multi sig wallet. 
First problem i enccountered: I wasnt really sure what a 2-of-3 schema was. You mean like this:
[https://imgur.com/a/2DBFp](url)

Then I pressed the option, insert private keys. Then I copied first the xprv address and then the first two xpub addresses i saw in the text. I couldnt press next then. I only could press next when i only used the xprv address. When i tried that i created a wallet but since i never could fill in the xpub's, thats the moment it went wrong. 
Also what i dont understand. You mentioned that you can find 2 xprv and 3xpub addresses. Then in the first wallet you need to use two xpubs and in the second you create also 2 xpubs. Which xpubs should i chose out of those 3?

I hope this made it a bit clearer for you. If not, just say and i try to explain it with more pictures.

**Comment by pooler** [comment]
First of all, you didn't explicitly say whether your Electrum Bitcoin wallet was 2FA. I'm going to suppose it is, and that you followed the instructions to restore if from seed.

Also, what versions of Electrum and Electrum-LTC are you using?

> I wasnt really sure what a 2-of-3 schema was. You mean like this: https://imgur.com/a/2DBFp

Yes.

> Then I pressed the option, insert private keys.

Just checking, it should be "Use public or private keys".

> Then I copied first the xprv address and then the first two xpub addresses i saw in the text. I couldnt press next then. I only could press next when i only used the xprv address.

You didn't insert all of the keys at once, did you? You need to insert just the first xprv for cosigner 1, just the second xpub for cosigner 2 and just the third xpub for cosigner 3. If at any point you can't press Next, it's because the input is wrong, so make sure you copied it right.

**Comment by klapinga** [comment]
> Also, what versions of Electrum and Electrum-LTC are you using?> 
electrum 2.9.3 and electrum 2.9.3.1

> Just checking, it should be "Use public or private keys".> 
yes, that option.

Thanks for the feedback. Im gonna try again with your tips and ill let you know the result.

**Comment by klapinga** [comment]
I tried it again and i managed to get my litecoin in my litecoin electrum wallet.
Thanks alot pooler for your help and patience :)
