### ISSUE TITLE
ltc electrum wallet can't connect

### ISSUE THREAD

**Issue by thetaateht** [pooler/electrum-ltc#75]
I have sent ltc from the exchange to my elctrum ltc wallet but the electrum wallet does not connect

**Comment by pooler** [comment]
Does it still not connect? It can take some time when you first run it, as it has to download and verify headers.

**Comment by pooler** [comment]
No response, closing.

**Comment by matkor** [comment]
For me it took more than 20 minutes of download on 512kbit/s link to switch to green "connected".
Any indication of download in progress or in console logs would be handy.

**Comment by panda8888** [comment]
Hello, 
I used to mine coins a couple of years ago (back in 2014), so i'm trying to recover some LTC i had stored in Electrum-LTC 1.9.8.5. I can see my balance, but i can't send any LTC. It keeps broadcasting... and i don't seem to get a connected to any servers. Do i have to upgrade to the latest version? If yes, how can i transfer the balance, or can i just update te server list in this version? 
Any help would be greatly appreciated! Thank you in advance!
