### ISSUE TITLE
Any way to avoid libpng warning: iCCP: known incorrect sRGB profile?

### ISSUE THREAD

**Issue by pingram3541** [pooler/electrum-ltc#76]
I found this thread in which it appears the actual png files have invalid iCCP chunks that unless removed will continue to throw this warning.

https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile#22747902

I know this doesn't effect the actual operation of this client but wondering if its an easy fix to eliminate the repetitive warning. Thx

**Comment by lzsaver** [comment]
`convert infile.png outfile.png`
I think this command can fix png-files.

**Comment by pingram3541** [comment]
Yeah I saw something with imagemagik using: mogrify -strip *.png

But I think this problem will keep resurfacing because the QR codes generated are (I believe) the png files it complains about.

**Comment by pooler** [comment]
This should be fixed by 7a40c89.
