### ISSUE TITLE
Linux client - Exception thrown: SSL handshake?

### ISSUE THREAD

**Issue by pingram3541** [pooler/electrum-ltc#77]
Noticed this output this morning when launching the wallet.  It still opens and prompts for password and appears to load but not sure I should trust proper normal operation of the wallet with this lingering in the background.

Background, I've had this wallet installed on this machine for a few weeks.  No recent s/w installed or upgrades of any kind, i.e. this wallet did not present this error yesterday and I've done nothing on this OS except boot up, execute wallet, transact 2 times, close wallet and shut down.  Same thing today, boot up, open wallet and now there are new errors below.  Any help appreciated. Thx

```
libpng warning: iCCP: known incorrect sRGB profile
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/electrum_ltc/interface.py", line 208, in run
    socket = self.get_socket()
  File "/usr/local/lib/python2.7/dist-packages/electrum_ltc/interface.py", line 128, in get_socket
    s = ssl.wrap_socket(s, ssl_version=ssl.PROTOCOL_SSLv23, cert_reqs=ssl.CERT_REQUIRED, ca_certs=ca_path, do_handshake_on_connect=True)
  File "/usr/lib/python2.7/ssl.py", line 943, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 611, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 840, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 0] Error
```

**Comment by pingram3541** [comment]
Odd, I tried rebooting, same result.  I tried closing and reopening the wallet several times after checking memory and processes and had the same result, then after simply visiting the .electrum-ltc/ folder and poking around and executing the wallet from within that directory the only error is the libpng as usual.  On subsequent wallet openings since, the Exception is not coming back.

**Comment by pooler** [comment]
As far as I can tell, this exception is the result of some issue when trying to connect to a server. As long as you can connect to other servers, I do not believe you should worry about it.

This is also not specific to Electrum-LTC. I get the same error in Electrum now and then.

**Comment by pingram3541** [comment]
Ah gotcha, thanks for confirming it should be safe to ignore this.  I had wondered if it was a remote server as it wasn't consistent.

I use Electrum too but had never come across this, good to know tho.  Thx again!

**Comment by dbeckwith** [comment]
I'm getting this same error every time I use the app. Any tips on what to try? Maybe deleting some config or something?
