### ISSUE TITLE
Invalid BIP39 Mnemonic generated

### ISSUE THREAD

**Issue by westonal** [pooler/electrum-ltc#78]
This mnemonic was generated by Electrum-LTC 2.8.5.3:

`despair neck garden cabbage one bless help lamp marriage can mushroom moon`

Don't worry I'm not actually using it!

It has an invalid checksum, try it on: https://iancoleman.github.io/bip39/

Is the mnemonic generated not a BIP39 one?

**Comment by pooler** [comment]
Electrum does not generate BIP39 seeds. More info here: http://docs.electrum.org/en/latest/seedphrase.html#motivation
