### ISSUE TITLE
missing features ? on ubuntu 16.04 version 2.9.3.1

### ISSUE THREAD

**Issue by cavapoo2** [pooler/electrum-ltc#85]
Should i have an address tab ?. i had to create a new wallet and input the watch addresses during initialsing setup phase. Should i be able to do this via the UI also (add more watch addresses).

Also maybe a seprate issue, but when i open wallet (./electrum_ltc) i have to use ./electrum_ltc -w path_to_specific_wallet to open up the wallet. Again should this be available via gui (pull down list) ?

I installed this just by downloading the tar.gz and untar to a directory, then just run the ./electrum_ltc.
i installed python-qt4 and ltc_scrypt also.

```
Exception in thread Thread-14:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/xxx/litewatch2/Electrum-LTC-2.9.3.1/lib/interface.py", line 208, in run
    socket = self.get_socket()
  File "/home/xxx/litewatch2/Electrum-LTC-2.9.3.1/lib/interface.py", line 140, in get_socket
    s = ssl.wrap_socket(s, ssl_version=ssl.PROTOCOL_SSLv23, cert_reqs=ssl.CERT_NONE, ca_certs=None)
  File "/usr/lib/python2.7/ssl.py", line 933, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 601, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 830, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 104] Connection reset by peer
```

![electrumpic](https://user-images.githubusercontent.com/3876950/33231091-50fb1efc-d1e7-11e7-8885-3f96c07d0dff.png)

**Comment by cavapoo2** [comment]
Im using ubuntu 16.04

**Comment by pooler** [comment]
> Should i have an address tab ?

Not by default. Click on View > Show Addresses to make it appear.

> Also maybe a seprate issue, but when i open wallet (./electrum_ltc) i have to use ./electrum_ltc -w path_to_specific_wallet to open up the wallet. Again should this be available via gui (pull down list) ?

File > Open.

If the problem is that you don't see a menu bar, then it's probably an OS issue. Maybe it's not visible until you press a specific key, or maybe it's missing because of some bug. A quick search brought up [this](https://bitcoin.stackexchange.com/questions/10482/no-menu-in-unbuntu-bitcoin-qt).

**Comment by cavapoo2** [comment]
thanks. seems like issue with the OS then.
