### ISSUE TITLE
compiling issue mac osx 10.12.6

### ISSUE THREAD

**Issue by 3ntranced** [pooler/electrum-ltc#86]
I just compiled the latest repo running all the commands under the Development version heading. I must have done something wrong because when I go to load transaction from file menu, electrum-ltc crashes and I get the following error in the terminal:

Traceback (most recent call last):
  File "/Volumes/csc/Downloads/electrum-ltc/gui/qt/main_window.py", line 2119, in do_process_from_file
    from electrum.transaction import SerializationError
ModuleNotFoundError: No module named 'electrum'
Abort trap: 6

**Comment by pooler** [comment]
Congratulations, you've found a bug! :-)
I've just pushed a fix, please try again.

**Comment by 3ntranced** [comment]
yes it works thank you
