### ISSUE TITLE
Verison 2.9.3.1 sha256sums gpg: BAD signature

### ISSUE THREAD

**Issue by terrelsa13** [pooler/electrum-ltc#87]
Hey,
I was trying to install Electurm-LTC 2.9.3.1. I was able to verify the digital signature. However when I try to verify the sha256sums i get the following:

```
$ gpg --verify Electrum-LTC-2.9.3.1.tar.gz.asc Electrum-LTC-2.9.3.1.tar.gz.DIGESTS.txt
gpg: Signature made Thu 17 Aug 2017 12:59:17 PM CDT using RSA key ID F1BE8FEA
gpg: BAD signature from "pooler <pooler@litecoinpool.org>"
```

I followed the [Verifying sha256sums (advanced)](https://www.torproject.org/docs/verifying-signatures.html.en#BuildVerification) instructions, substituting the Electurm-LTC data in place of the Tor data. I suspect I likely don't understand this enough to see what I'm doing wrong. But from the "Important Notice" on the website, this seems like a situation where it's better to ask than to assume everything is ok.

Linux Mint 18.2
Electrum-LTC 2.9.3.1

**Screenshots of all commands:**
![gpgverify0](https://user-images.githubusercontent.com/16886488/33238226-e17b7384-d24e-11e7-870b-810f4aca9ed1.png)
![gpgverify1](https://user-images.githubusercontent.com/16886488/33238227-e507aea0-d24e-11e7-900c-9f97c6ebe0c7.png)

**Comment by pooler** [comment]
The two files in your command are mismatched. No signature is provided for the `DIGESTS` file, and you can't just use the signature for another file. What matters is that, as your screenshot shows near the end, the signature for the archive itself is good.
