### ISSUE TITLE
Recovery + Password not working

### ISSUE THREAD

**Issue by JaronC123** [pooler/electrum-ltc#88]
Dear readers/developers

Recently i tried to send some Litecoin to another wallet which required a password. Since i wrote all of this down on an organized paper i thought that i wouldn't find any problems. However when i typed the password it was wrong. I tried multiple possibilities but was unable to process my transaction.

After a while i tried to recover my litecoin on different wallet applications because i thought i lost my password for my Electrum one. I never was able to recover my wallet with the **right 12 word phrase** which i **tried multiple times** as well. I also tried this on Electrum Litecoin wallet as well but the next button was always grayed out. However when i put a letter in a word that didn't belong there it would say which word had a spelling mistake.

I always get the message that my 12 word wallet phrase is not valid. However i can still access it via my laptop but i am restricted by the password.

Is this a bug in the system or is my wallet some how out of sync? Thank you for reading and sharing your thoughts.
(If you find some spelling mistakes i apologize for that since English is not my main language.)

**Comment by pooler** [comment]
What versions did you use?

> I also tried this on Electrum Litecoin wallet as well

"Also"? Do you mean that you tried restoring from seed with something other than Electrum-LTC?

> Is this a bug in the system or is my wallet some how out of sync?

I've never had issues restoring from seed. And synchronization should have nothing to do with it (seeds can be validated offline).

**Comment by sunk818** [comment]
Did you copy paste seed words or type them out? 
Pooler does case matter?

**Comment by pooler** [comment]
>  Pooler does case matter?

No.

**Comment by JaronC123** [comment]
@pooler 
> What versions did you use?

I used version 2.9.3.1 to restore my wallet on a new computer. The same version was used to create the wallet.

> "Also"? Do you mean that you tried restoring from seed with something other than Electrum-LTC?

The seed was originaly created with Electrum wallet and was used to restore on version 2.9.3.1 which failed. I also tried other popular wallet programs to check if they worked on those, which also failed. But to answer your question i first of tried restoring the seed with Electrum-LTC wallet.

@sunk818 

> Did you copy paste seed words or type them out?

I did both, first type them out a few times and after trying over and over i started using copy and paste.

**Comment by pooler** [comment]
> > "Also"? Do you mean that you tried restoring from seed with something other than Electrum-LTC?
>
> The seed was originaly created with Electrum wallet and was used to restore on version 2.9.3.1 which failed.

Do you mean the Bitcoin Electrum here? If so, which version, and what are you trying to do exactly?
Does this mean that the seed in question was never loaded in Electrum-LTC, and that you're therefore not really "restoring" it?

**Comment by JaronC123** [comment]
> Do you mean the Bitcoin Electrum here? If so, which version, and what are you trying to do exactly?

No i never used the Bitcoin Electrum, only the Electrum-LTC which i used to generate my seed to store my Litecoins. When i try to recover my wallet seed, i do this using Electrum-LTC. But the original seed from Electrum-LTC that i want to recover is not working. So i have access to the Electrum-LTC wallet with my laptop but that one is restricted by a password that somehow doesn't work either, however all that information was written down by me which i got on paper (same with my seed). So the thing is that i tried to place everything on my desktop to be able to use my Electrum-LTC wallet again without any password restrictions.
> Does this mean that the seed in question was never loaded in Electrum-LTC, and that you're therefore not really "restoring" it?

The seed was always loaded in Electrum-LTC.

**Comment by pooler** [comment]
I think I understand your situation a little better now. However, I'm unable to reproduce the issue, and for obvious reasons I can't ask you to reveal the seed, so I'm not sure how I can help you.

**Comment by JaronC123** [comment]
> I think I understand your situation a little better now. However, I'm unable to reproduce the issue, and for obvious reasons I can't ask you to reveal the seed, so I'm not sure how I can help you.

I have no problem with sharing my seed in private with you, let me now what you think.

**Comment by pooler** [comment]
> I have no problem with sharing my seed in private with you, let me now what you think.

I can have a look if you want, but if the wallet in questions contains any funds I take no responsibility for their safety. You may want to send me an email (pooler at litecoinpool dot org). If you use PGP, my key is available [here](https://pgp.mit.edu/).

**Comment by JaronC123** [comment]
@pooler 

I sent you a mail with the following subject: "Not able to use recovery phrase for Electrum-LTC".

I appreciate you taking the time to look in to this issue.

**Comment by pooler** [comment]
The seed I received from @JaronC123 is indeed invalid (it has an invalid version prefix), and as far as I can tell it could not have been produced as-is by Electrum-LTC. The most probable hypothesis appears to be that the seed was transcribed incorrectly.

While I was there I tried some very basic word substitutions and permutations, but none of the resulting seeds matched the master public key that was sent to me. If you really care about this wallet, you might want to try conducting an extensive search.

**Comment by JaronC123** [comment]
Hi

Since the wallet file is not encrypted but only secured by a password, could it be possible to crack the file in order to by pass the password on it?


Op 6 dec. 2017 om 15:50 heeft pooler <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


The seed I received from @JaronC123<https://github.com/jaronc123> is indeed invalid (it has an invalid version prefix), and as far as I can tell it could not have been produced as-is by Electrum-LTC. The most probable hypothesis appears to be that the seed was transcribed incorrectly.

While I was there I tried some very basic word substitutions and permutations, but none of the resulting seeds matched the master public key that was sent to me. If you really care about this wallet, you might want to try conducting an extensive search.

**Comment by pooler** [comment]
Sure, you can try to recover the password via brute force, but you'll only stand a chance if the password is a weak one.

**Comment by JaronC123** [comment]
Well i sure is not a strong password? Atleast the one i wrote down. However i am sure it doesn’t have any special combination, so it shouldn’t be that hard to bruteforce it.

The problem is that i am no hacker at all so i don’t know which kind of bruteforce program should work on the wallet. Do you have any tips about this?



Op 12 dec. 2017 om 13:34 heeft pooler <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Sure, you can try to recover the password via brute force, but you'll only stand a chance if the password is a weak one.

**Comment by JaronC123** [comment]
I will put the wallet file in this e-mail maby if that helps. In the meanwhile i am going to try putting a laptop to Kali Linux to try brute forcing. By the way, also followed your advice and kept a big search to find any more valid information about my wallet but without success.

________________________________
Van: jaron carael <jaron.carael@hotmail.com>
Verzonden: dinsdag 12 december 2017 16:13:11
Aan: pooler/electrum-ltc
Onderwerp: Re: [pooler/electrum-ltc] Recovery + Password not working (#88)

Well i sure is not a strong password? Atleast the one i wrote down. However i am sure it doesn’t have any special combination, so it shouldn’t be that hard to bruteforce it.

The problem is that i am no hacker at all so i don’t know which kind of bruteforce program should work on the wallet. Do you have any tips about this?



Op 12 dec. 2017 om 13:34 heeft pooler <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Sure, you can try to recover the password via brute force, but you'll only stand a chance if the password is a weak one.

**Comment by pooler** [comment]
@JaronC123, sorry, I can't help you with password recovery.
