### ISSUE TITLE
I am trying to send bitcoins with my electrum first but receive error"server did not answer

### ISSUE THREAD

**Issue by dylanbedard** [pooler/electrum-ltc#89]
I installed my electrum wallet 2 days ago(latest version) and received coins ok. i tried sending it  and i get the error "error : servr did not answer"

I went to the electrum website but they dont have any support emails on it so now i am lost wiht what to do. hope this forum can help me out.

**Comment by pooler** [comment]
> hope this forum can help me out.

This is not a help forum, it is an issue tracker. If you don't suspect a bug, you shouldn't post here. You can ask for help on actual [forums](https://litecointalk.org/) or on [reddit](https://www.reddit.com/r/litecoin).

> I am trying to send bitcoins

Did you mean litecoins?

> i tried sending it and i get the error "error : servr did not answer"

First make sure that you're using the latest version. Then open the network dialog and make sure you are connected and that the blockchain is synchronized. If needed, try connecting to a different server manually.
