### ISSUE TITLE
fee slider bug overestimating miner fees

### ISSUE THREAD

**Issue by montvid** [pooler/electrum-ltc#90]
The miner fee is 0.001 ltc/kb now to get to the next block as they are historically never full but the wallet fee slider slides all the way to 0.01 ltc/kb. So basically the fee estimation is broken. It needs to be fixed asap as some people may be robbed of their ltc if they use the slider.

As you can see there is a real problem of people paying too high miner fees:
https://chain.so/ltc
https://bitinfocharts.com/comparison/litecoin-transactionfees.html#3m

**Comment by pooler** [comment]
Fee estimation has gotten much better since servers started upgrading to Litecoin Core 0.15.
The fee slider values have also been lowered. Closing.
