### ISSUE TITLE
laptop camera for QR code

### ISSUE THREAD

**Issue by brucejacob** [pooler/electrum-ltc#91]
Presumably this is supposed to work like Electrum (BTC), in which there's a button to hit in the send-address field that engages the laptop's camera to import QR codes. In Electrum, there are two buttons to choose from: the leftmost one is the camera; the rightmost one looks for a file on disk. In your send-address field, there are two buttons: the one on the right looks for a file on disk, so I assmue the leftmost one is supposed to engage the camera. However, when I hit the button, the app crashes, every time.

Version 2.9.3.1 on Linux (Tails)

**Comment by pooler** [comment]
It should work (or not work) exactly as in Electrum. What version of Electrum are you comparing Electrum-LTC 2.9.3.1 to?

**Comment by brucejacob** [comment]
Electrum-3.0.2 … I know, not fair to compare v2 to v3, but I thought it would help.

--
Prof. Bruce Jacob - blj@ece.umd.edu - www.ece.umd.edu/~blj
Electrical & Computer Engineering, University of Maryland, College Park

**Comment by pooler** [comment]
The git repo is currently on par with upstream, so you may want to give it a try.

**Comment by brucejacob** [comment]
grazie mille! Thank you so much!
--
Prof. Bruce Jacob - blj@ece.umd.edu - www.ece.umd.edu/~blj
Electrical & Computer Engineering, University of Maryland, College Park
