### ISSUE TITLE
Consuming 100% CPU

### ISSUE THREAD

**Issue by togores** [pooler/electrum-ltc#93]
![cpu](https://user-images.githubusercontent.com/409187/33823433-4b084bde-de42-11e7-8ad9-d1cc0699a8ce.png)

Also my transaction show as not verified, despite being connected to the network.

**Comment by pooler** [comment]
What OS/distro/version are you using?
Please provide the exact steps that you followed to install Electrum-LTC.

**Comment by togores** [comment]
Ubuntu 16.04 LTS
Kernel 4.10.0-42-generic

I just downloaded the package, extracted to a folder and ran from there.

**Comment by pooler** [comment]
You should install the `ltc_scrypt` package, otherwise Electrum-LTC will use the pure Python fallback, and block verification will be very slow.

```
sudo apt-get install python-pip python-dev
sudo pip2 install ltc_scrypt
```

**Comment by togores** [comment]
Fixed
