### ISSUE TITLE
Disconnect

### ISSUE THREAD

**Issue by JackMarginalov** [pooler/electrum-ltc#94]
My Electrum-ltc wallet does not connect to the network. 
Default settings.  What could be the problem?

**Comment by pooler** [comment]
It can take some time when you first run it, as it has to download and verify headers. If it takes more than a few minutes, please state what OS you are using and how exactly you installed Electrum-LTC. I'd also like to know what the Network dialog reports, and if you tried connecting manually to a different server.

**Comment by Alexpr27** [comment]
Hello. My Electrum-ltc wallet does not connect to the network and it's passed morethen 30 min.
I'm using portable version with win 7 64

**Comment by Alexpr27** [comment]
About 1 hour passed and it's working now.

**Comment by pooler** [comment]
How fast is your internet connection? The block headers are a 100 MB download.

**Comment by Alexpr27** [comment]
My speed about 30-60MB

**Comment by pooler** [comment]
> My speed about 30-60MB

Per hour? Then the case is closed. :-)

Seriously, there could have been an issue during the initial download. Maybe the download was interrupted, and Electrum started requesting block chunks from peers one by one, which would have taken a long time.
At any rate, the initial synchronization process has been changed in the git repo, and the initial download is no longer necessary, so unless you have reason to believe that the problem lies elsewhere I think we can close this ticket.

**Comment by ceruleanfirm** [comment]
Hi,
Same issue,
installed 20 (twenty) hours ago with pip2 :
pip2 install https://electrum-ltc.org/download/Electrum-LTC-2.9.3.1.tar.gz
I tried with automatic server,
and with 5 or 6 differents servers in the list
the daemon is running well,
the path and the wallet exists (yeah really : )
but it does not connect.
firewall is off. 
I'm on fedora 25
??
electrum (for btc) works fine

**Comment by pooler** [comment]
Could you please take a screenshot of the Network dialog?

**Comment by ceruleanfirm** [comment]
Thanks for reply,
I have now a connection with this server :
electrumx.nmdps.net:9434
I can see it with tcpdump
It was not the case yesterday
It seems to be the only one,
I hope it is just now a question of time.
But the button is still red (and still quoted "not connected")

**Comment by ceruleanfirm** [comment]
Hi,
still not connected : (
and (ooops!) I realise that there is no dialog, 
my station is sending only SYN paquets, there is no answer from any server I can choose ...

13:03:59.720836 IP wtf.41304 > 31-208-128-61.cust.bredband2.com.50004: Flags [S], seq 2002623647, win 29200, options [mss 1460,sackOK,TS val 3963569789 ecr 0,nop,wscale 7], length 0

The only thing "better" is that I can reach more servers than yesterday ...

**Comment by adipop20** [comment]
tor electrum xvg 2.4.1 - not connected, bought some verge and only after the transaction finished I realised nothing shows:(
not a tech guy myself, too afraid to reinstall to see what happens:)

**Comment by adipop20** [comment]
update: Problem solved - I've tried everything I could find on forums and eventualy it connected and shows the balance, however no idea what worked:))
last ops: unchecked Autoconect then changed the address electo-verge.xyz:50002 didn't seem to work, so I checked the "use ssl" - socks5 /127.0.0.1/ 9150 setting and minutes after it just connected 🥇

**Comment by ceruleanfirm** [comment]
Yeah solved too for days ...
I had forgotten the port ...
Sorry about that pooler ...
Thx anyway !
: )

**Comment by pooler** [comment]
No response from OP, closing.
