### ISSUE TITLE
Confirmed transaction remains as "Not Verified"

### ISSUE THREAD

**Issue by davidlesches** [pooler/electrum-ltc#99]
Sent a little LTC as a test from Coinbase to Wallet yesterday, has 400+ confirmations but still showing as "Not Verified"

I've changed the selected network server multiple times and re-synced; I've also destroyed and recreated the wallet via the seed. Still 'Not Verified'.

Transaction: https://chain.so/tx/LTC/cb5b07d6daa7ab0e22fa65201d799af3f440f5069cc16a77fdaf5bf9ee7c39d0

Is this a bug?

**Comment by sunk818** [comment]
Shows confirmed now.

**Comment by davidlesches** [comment]
@sunk818 but it still shows as Not Verified in my E-LTC wallet. Screenshot: https://cl.ly/362o2C1o0p12/Image%202017-12-13%20at%2012.18.38%20PM.png

**Comment by davidlesches** [comment]
It just changed to Verified. I'm not sure I understand this, but anyway.

**Comment by sunk818** [comment]
I can only think that LiteCoin has a lot of activity recently due to price pump. Not sure what kind of transaction fee you (high, medium, low), but perhaps miners chose not to include your transaction in a block until the high transaction fees were processed first.

**Comment by pooler** [comment]
Did you try connecting to a different server?

**Comment by tom-seddon** [comment]
I'm having the same problem with Electrum 2.9.3.1.

I've tried connecting to a few different servers and restarting Electrum-LTC each time, but it didn't make a difference.

Here's a transaction I sent that's showing as Not Verified: https://chain.so/tx/LTC/4a1e497587e95fd4b5bd7accb28c11cdc705863d51639c608a4fdccb67c199db (72 confirmations at time of writing)

I was able to spend some of it anyway: https://chain.so/tx/LTC/f7710377c5be095d4785ed9945ad2d679e90285af16fa06b7f224b8892384214 (also Not Verified, despite 48 confirmations at time of writing)

Thanks,

--Tom

**Comment by pooler** [comment]
Could you provide a screenshot of the Network dialog?

**Comment by tom-seddon** [comment]
OK, problem solved (for me at any rate). After actually looking more closely at the stuff on that dialog, and consulting the help text for each one, I noticed that the `Blockchain` value was rather behind the block number of either of my transactions, but increasing. And after waiting for it to catch up, the transactions came up as verified.

So, that's that. I didn't think to do this before, as the webpage says that Electrum-LTC requires no sync process... but obviously there's some data that needs to be downloaded, and that might take long enough to download that you'll get confusing results during the process. Perhaps this wording could be clarified?

Thanks,

--Tom

**Comment by pooler** [comment]
Yes, I agree that the wording on the website is confusing. I'll make sure it gets fixed.

By the way, it is worth noting that the initial synchronization process has been changed in the git repo, and the initial download is no longer necessary.

**Comment by ExecSam** [comment]
> Yes, I agree that the wording on the website is confusing. I'll make sure it gets fixed.
> 
> By the way, it is worth noting that the initial synchronization process has been changed in the git repo, and the initial download is no longer necessary.

9 years later this is still not resolved. 

<img width="806" height="157" alt="Image" src="https://github.com/user-attachments/assets/9426c37c-c794-4313-9c6d-39d443c1100a" />

Was this ever actually fixed??
